Repository camel-ai/camel, pull requests merged in 2023-11, with the labels that each got.

#349 [Workflow] Add mypy check to pre-commit
  .github/workflows/linting.yml
  .github/workflows/pre_commit.yml
  .pre-commit-config.yaml
Labels: workflow

#358 Instruction for HF deployment
  apps/agents/README.md
Labels: UI

#359 chores: fix tests fail because of pre-commit changing
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: CI/CD

#334 Update weather function API by using pyowm
  .github/workflows/pytest_package.yml
  camel/functions/__init__.py
  camel/functions/data_io_functions.py
  camel/functions/search_functions.py
  camel/functions/weather_functions.py
  examples/function_call/role_playing_with_function.py
  poetry.lock
  pyproject.toml
  test/functions/test_weather_function.py
Labels: API, New Feature

#361 feature(types): Add new OpenAI APIs
  .github/actions/camel_install/action.yml
  camel/types/enums.py
  test/models/test_model_factory.py
  test/models/test_openai_model.py
Labels: API

#366 [BUG] Solved the name inconsistancy bugs for ChatAgent
  camel/agents/chat_agent.py
  camel/agents/critic_agent.py
  camel/agents/embodied_agent.py
  camel/agents/role_assignment_agent.py
  camel/agents/task_agent.py
  camel/societies/role_playing.py
  camel/utils/commons.py
  examples/ai_society/babyagi_playing.py
  examples/ai_society/role_playing.py
  examples/ai_society/role_playing_multi_lingual.py
  examples/ai_society/task_generation.py
  examples/code/generate_meta_data.py
  examples/code/role_playing.py
  examples/code/task_generation.py
  examples/embodiment/hugging_face_tool.py
  examples/evaluation/single_agent.py
  examples/function_call/role_playing_with_function.py
  examples/misalignment/single_agent.py
  examples/open_source_models/role_playing_with_open_source_model.py
  examples/role_description/role_generation.py
  examples/role_description/role_playing_with_role_description.py
  examples/single_agent.py
  examples/summarization/gpt_solution_extraction.py
  examples/test/test_ai_society_example.py
  examples/test/test_babyagi_example.py
  examples/test/test_code_example.py
  examples/test/test_role_description_example.py
  examples/translation/translator.py
  test/agents/test_babyagi_playing.py
  test/agents/test_chat_agent.py
  test/agents/test_role_assignment_agent.py
  test/agents/test_role_playing.py
  test/agents/test_task_agent.py
Labels: Agent

#379 Update `update_lisences.py`
  licenses/update_license.py
Labels: Lisence, CI/CD

#376 feat(embeddings): Add text embedding feature
  camel/agents/chat_agent.py
  camel/embeddings/__init__.py
  camel/embeddings/base.py
  camel/embeddings/openai_embedding.py
  camel/models/openai_model.py
  camel/types/__init__.py
  camel/types/enums.py
  camel/utils/commons.py
  test/embeddings/test_openai_embedding.py
Labels: enhancement

#384 fix(embeddings): Fix embeddings names
  camel/embeddings/base.py
  camel/embeddings/openai_embedding.py
  camel/types/enums.py
  test/embeddings/test_openai_embedding.py
Labels: Embeddings

#391 docs: Updated citation to neurips format
  README.md
Labels: documentation
