Repository camel-ai/camel, pull requests merged in 2023-09, with the labels that each got.

#245 Integrate Open-source Models
  README.md
  camel/agents/chat_agent.py
  camel/agents/critic_agent.py
  camel/agents/task_agent.py
  camel/configs.py
  camel/messages/base.py
  camel/models/__init__.py
  camel/models/base_model.py
  camel/models/model_factory.py
  camel/models/open_source_model.py
  camel/models/openai_model.py
  camel/models/stub_model.py
  camel/typing.py
  camel/utils/__init__.py
  camel/utils/functions.py
  camel/utils/token_counting.py
  examples/open_source_models/role_playing_with_open_source_model.py
  examples/test/test_ai_society_example.py
  pyproject.toml
  test/agents/test_chat_agent.py
  test/agents/test_embodied_agent.py
  test/agents/tool_agents/test_hugging_face_tool_agent.py
  test/messages/test_message_base.py
  test/models/test_open_source_model.py
  test/models/test_openai_model.py
Labels: Model

#282 Add `wechat` account
  README.md
  camel/functions/search_functions.py
Labels: documentation

#247 Generate the roles and role description
  camel/agents/__init__.py
  camel/agents/role_assignment_agent.py
  camel/prompts/__init__.py
  camel/prompts/ai_society.py
  camel/prompts/role_description_prompt_template.py
  camel/prompts/task_prompt_template.py
  camel/societies/role_playing.py
  camel/typing.py
  examples/role_description/role_generation.py
  examples/role_description/role_playing_with_role_description.py
  examples/test/test_role_description_example.py
  test/agents/test_role_assignment_agent.py
  test/prompts/test_role_description_prompt_template.py
Labels: enhancement

#284 chore: fix typo in python_interpreter.py
  camel/utils/python_interpreter.py
Labels: documentation

#281 [New Feature] Add_Data_IO_Functions
  camel/functions/data_io_functions.py
  poetry.lock
  pyproject.toml
  test/data_samples/test_hello.docx
  test/data_samples/test_hello.html
  test/data_samples/test_hello.json
  test/data_samples/test_hello.pdf
  test/data_samples/test_hello.txt
  test/data_samples/test_hello_multi.docx
  test/data_samples/test_hello_multi.pdf
  test/functions/test_data_io_functions.py
Labels: New Feature

#289 [Fix] More coverage for python interpreter
  CONTRIBUTING.md
  camel/utils/python_interpreter.py
  test/utils/test_python_interpreter.py
Labels: Test
