Repository camel-ai/camel, pull requests merged in 2024-11, with the labels that each got.

#1137 feat: Add support for Qwen model platform (#1033)
  camel/configs/__init__.py
  camel/configs/qwen_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/qwen_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/qwen_model_example.py
  test/models/test_qwen_model.py
Labels: Model

#1099 feat: add github funcs with github toolkit
  camel/toolkits/github_toolkit.py
  examples/toolkits/github_toolkit.py
  test/toolkits/test_github_toolkit.py
Labels: enhancement

#1147 feat: Qdrant enhancement
  camel/storages/vectordb_storages/qdrant.py
  test/storages/vector_storages/test_qdrant.py
Labels: enhancement

#1155 chore: Priority critic and task agent kwargs in RolePlaying
  camel/societies/role_playing.py
Labels: enhancement

#1154 doc: pdate `readme.md` with features and some main feature code sinppets
  README.md
Labels: Readme

#1126 feat: WolframAlpha more detailed output
  camel/toolkits/search_toolkit.py
  test/toolkits/test_search_functions.py
Labels: enhancement

#1161 feat: add param extra_payload for VectorRetriever.process()
  camel/retrievers/vector_retriever.py
  test/retrievers/test_cohere_rerank_retriever.py
Labels: enhancement

#1165 fix: output_language setting in ChatAgent
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
  test/agents/test_chat_agent.py
Labels: bug

#1167 fix: init_message use current sys msg
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
Labels: bug

#1168 fix: update `n` type in OpenAI Model
  camel/models/openai_model.py
Labels: bug

#1170 fix: RolePlaying model setting would be override by default model
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/societies/role_playing.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
Labels: bug

#1144 feat: Sharegpt conversion
  camel/messages/__init__.py
  camel/messages/base.py
  camel/messages/conversion/__init__.py
  camel/messages/conversion/models.py
  camel/messages/conversion/sharegpt/__init__.py
  camel/messages/conversion/sharegpt/function_call_formatter.py
  camel/messages/conversion/sharegpt/hermes/__init__.py
  camel/messages/conversion/sharegpt/hermes/hermes_function_formatter.py
  camel/messages/func_message.py
  examples/conversion.py
  test/messages/test_func_message.py
  test/messages/test_message_base.py
Labels: New Feature

#1178 chore: add mode Qwen models, fix doc bug
  camel/types/enums.py
  docs/cookbooks/agents_with_rag.ipynb
  docs/key_modules/models.md
  docs/key_modules/workforce.md
  examples/models/qwen_model_example.py
  test/models/test_model_factory.py
  test/models/test_qwen_model.py
Labels: enhancement

#1162 feat: Wolfram alpha records SBSHintStep info
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
Labels: enhancement

#1140 feat: synthesize the execution of tool calling
  camel/agents/chat_agent.py
  camel/toolkits/__init__.py
  camel/toolkits/function_tool.py
  camel/toolkits/whatsapp_toolkit.py
  docs/cookbooks/agents_with_tools.ipynb
  examples/toolkits/generate_openai_tool_schema.py
  examples/toolkits/synthesize_function_execution.py
  test/toolkits/test_generate_openai_tool_schema.py
  test/toolkits/test_synthesize_output.py
Labels: New Feature

#1182 chore: upadte asknews example and api key setting
  camel/toolkits/ask_news_toolkit.py
  examples/toolkits/ask_news_toolkit.py
Labels: enhancement

#1188 chore: minor fix and update
  camel/models/samba_model.py
  camel/societies/workforce/workforce.py
  camel/toolkits/__init__.py
  camel/toolkits/dalle_toolkit.py
  camel/toolkits/function_tool.py
  camel/toolkits/math_toolkit.py
  camel/toolkits/search_toolkit.py
  camel/toolkits/twitter_toolkit.py
  camel/toolkits/weather_toolkit.py
  docs/key_modules/tools.md
  examples/toolkits/post_weather_on_twitter.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
Labels: enhancement

#1176 feat: Update guide for applying and using keys in camel
  .env
  .gitignore
  README.md
  poetry.lock
Labels: documentation, enhancement

#932 feat: Integrate cohere models
  camel/configs/__init__.py
  camel/configs/cohere_config.py
  camel/models/__init__.py
  camel/models/cohere_model.py
  camel/models/model_factory.py
  camel/retrievers/cohere_rerank_retriever.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  examples/models/cohere_model_example.py
  examples/models/role_playing_with_cohere.py
  poetry.lock
  pyproject.toml
  test/models/test_cohere_model.py
Labels: Model, New Feature

#1198 feat: support openai structured output
  camel/agents/chat_agent.py
  camel/configs/openai_config.py
  camel/models/openai_model.py
  camel/types/__init__.py
  camel/types/openai_types.py
  examples/models/openai_structured_output_example.py
Labels: Model

#1200 feat: Add human toolkit for human interaction with the agent (#1158)
  camel/toolkits/__init__.py
  camel/toolkits/human_toolkit.py
  examples/toolkits/human_toolkit.py
Labels: Agent

#1163 feat: Add Runtime for tool calling
  .gitignore
  camel/runtime/__init__.py
  camel/runtime/api.py
  camel/runtime/base.py
  camel/runtime/configs.py
  camel/runtime/docker_runtime.py
  camel/runtime/llm_guard_runtime.py
  camel/runtime/remote_http_runtime.py
  camel/runtime/utils/__init__.py
  camel/runtime/utils/function_risk_toolkit.py
  camel/runtime/utils/ignore_risk_toolkit.py
  camel/toolkits/code_execution.py
  camel/toolkits/search_toolkit.py
  examples/runtime/code_execution_with_docker_runtime.py
  examples/runtime/code_execution_with_llm_guard_runtime.py
  examples/runtime/docker_runtime.py
  examples/runtime/docker_runtime_with_tasks.py
  examples/runtime/remote_http_runtime.py
  examples/toolkits/github_toolkit.py
  poetry.lock
  pyproject.toml
  test/runtime/test_code_execution_with_llm_guard_runtime.py
  test/runtime/test_docker_runtime.py
  test/runtime/test_remote_http_runtime.py
Labels: New Feature

#883 feat: Integrate video reading
  .gitignore
  camel/toolkits/__init__.py
  camel/toolkits/video_toolkit.py
  examples/vision/duckduckgo_video_object_recognition.py
  examples/vision/web_video_description_extractor.py
  examples/vision/web_video_object_recognition.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_video_function.py
Labels: New Feature

#1209 chore: update doc and small polish
  CONTRIBUTING.md
  README.md
  camel/personas/persona.py
  camel/personas/persona_hub.py
  docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/index.rst
Labels: documentation

#1225 feat: Update Gemini implementation with openai compatibility
  camel/agents/chat_agent.py
  camel/configs/gemini_config.py
  camel/models/gemini_model.py
  examples/models/role_playing_with_cohere.py
  test/models/test_gemini_model.py
Labels: enhancement

#1217 feat: support deepseek model in camel
  camel/configs/__init__.py
  camel/configs/deepseek_config.py
  camel/models/__init__.py
  camel/models/deepseek_model.py
  camel/models/model_factory.py
  camel/types/enums.py
  docs/key_modules/models.md
  examples/models/deepseek_model_example.py
  examples/toolkits/github_toolkit.py
  poetry.lock
  test/models/test_deepseek_model.py
Labels: Model

#1060 feat: Support Text to BaseModel
  camel/schemas/__init__.py
  camel/schemas/base.py
  camel/schemas/openai_converter.py
  camel/utils/__init__.py
  camel/utils/response_format.py
  examples/schema_outputs/openai_converter_example.py
  test/schema_outputs/test_openai_converter.py
Labels: New Feature

#1223 feat: Openai compatible embedding
  camel/embeddings/__init__.py
  camel/embeddings/openai_compatible_embedding.py
  examples/embeddings/openai_compatible_embedding_example.py
  test/embeddings/test_openai_compatible_embedding.py
Labels: New Feature, Embeddings

#1247 fix: bug fix and small enhance
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/embeddings/openai_compatible_embedding.py
  camel/types/enums.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  docs/key_modules/models.md
  examples/embeddings/openai_compatible_embedding_example.py
  poetry.lock
  pyproject.toml
  test/embeddings/test_openai_compatible_embedding.py
  test/models/test_qwen_model.py
Labels: bug

#1190 Add ModelManager to schedule calls between different model backend
  camel/agents/chat_agent.py
  camel/models/__init__.py
  camel/models/model_manager.py
  examples/models/model_manger.py
  test/agents/test_chat_agent.py
  test/models/test_model_manager.py
Labels: New Feature

#1246 feat: Added other interpreters to CodeExecutionToolkit
  camel/toolkits/code_execution.py
  test/toolkits/test_code_execution.py
Labels: New Feature

#1251 fix: that user cannot see question when using human_toolkit
  camel/toolkits/human_toolkit.py
Labels: bug

#1253 feat: added manual addition of filename metadata and normalized extra…
  camel/retrievers/vector_retriever.py
  test/retrievers/test_vector_retriever.py
Labels: enhancement
