Repository camel-ai/camel, pull requests merged in 2024-09, with the labels that each got.

#845 feat: Integrate Reka model
  .github/actions/camel_install/action.yml
  .github/workflows/build_package.yml
  .github/workflows/documentation.yml
  .github/workflows/pre_commit.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  README.md
  camel/agents/chat_agent.py
  camel/configs/__init__.py
  camel/configs/reka_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/reka_model.py
  camel/storages/object_storages/amazon_s3.py
  camel/types/enums.py
  docs/get_started/setup.md
  examples/models/reka_model_example.py
  examples/test/bots/test_telegram_bot.py
  poetry.lock
  pyproject.toml
  test/models/test_reka_model.py
Labels: Model, P0

#861 docs: Add code review guide
  CONTRIBUTING.md
Labels: documentation

#885 docs: Update installation instructions
  README.md
Labels: enhancement

#892 release: v0.1.6.8
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release

#895 feat: Add max_characters setting to RAG
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/retrievers/auto_retriever.py
  camel/retrievers/vector_retriever.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: enhancement

#904 feat: Add `top_k` and `similarity_threshold` to RetrievalToolkit
  camel/retrievers/auto_retriever.py
  camel/retrievers/vector_retriever.py
  camel/toolkits/retrieval_toolkit.py
  camel/utils/constants.py
Labels: enhancement

#903 fix: embedding dimensions setting
  camel/embeddings/openai_embedding.py
Labels: bug

#881 feat: add firecrawl map endpoint
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/loaders/firecrawl_reader.py
  examples/loaders/firecrawl_example.py
  poetry.lock
  pyproject.toml
  test/loaders/test_firecrawl.py
Labels: enhancement, New Feature

#886 feat: integrate reddit toolkit
  camel/toolkits/__init__.py
  camel/toolkits/reddit_toolkit.py
  examples/function_call/reddit_examples.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_reddit_functions.py
Labels: New Feature

#916 feat: Update message append logic for `handle_stream_response`
  camel/agents/chat_agent.py
Labels: bug, enhancement, Model

#920 feat: SambaVerse API support
  camel/agents/chat_agent.py
  camel/configs/__init__.py
  camel/configs/samba_config.py
  camel/models/model_factory.py
  camel/models/ollama_model.py
  camel/models/samba_model.py
  camel/types/enums.py
  examples/models/samba_model_example.py
  test/models/test_samba_model.py
Labels: Model

#912 feat: Subprocess support for Ollma and vllm
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/models/ollama_model.py
  camel/models/vllm_model.py
  docs/conf.py
  docs/get_started/setup.md
  examples/models/ollama_model_example.py
  examples/models/vllm_model_example.py
  pyproject.toml
Labels: Model

#830 Feat: Add external tool support to `ChatAgent` & Refactor
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/types/enums.py
  camel/utils/commons.py
  camel/utils/constants.py
  docs/conf.py
  docs/get_started/setup.md
  examples/external_tools/use_external_tools.py
  poetry.lock
  pyproject.toml
  test/agents/test_chat_agent.py
Labels: enhancement, Agent

#930 feat: Add SambaNova Cloud API support
  camel/configs/__init__.py
  camel/configs/samba_config.py
  camel/models/ollama_model.py
  camel/models/samba_model.py
  camel/models/vllm_model.py
  examples/models/samba_model_example.py
Labels: Model, P0

#919 Fix: Google Maps Toolkit Incompatible Parameters
  camel/toolkits/google_maps_toolkit.py
  poetry.lock
  test/toolkits/test_google_maps_function.py
Labels: bug

#936 feat: Support openai o1 models
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/types/enums.py
  camel/utils/token_counting.py
  docs/conf.py
  docs/get_started/setup.md
  poetry.lock
  pyproject.toml
  test/models/test_openai_model.py
Labels: Model

#901 docs: Add tasks cookbook
  cookbooks/task_generation.ipynb
  examples/tasks/task_generation.py
Labels: documentation

#938 fix: Remove FUNCS and GPT 3.5 Turbo in examples
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/toolkits/__init__.py
  camel/toolkits/google_maps_toolkit.py
  camel/toolkits/linkedin_toolkit.py
  camel/toolkits/open_api_toolkit.py
  camel/toolkits/reddit_toolkit.py
  camel/toolkits/retrieval_toolkit.py
  camel/toolkits/slack_toolkit.py
  camel/toolkits/twitter_toolkit.py
  docs/agents/single_agent.md
  docs/conf.py
  docs/get_started/setup.md
  examples/ai_society/role_playing_multiprocess.py
  examples/ai_society/role_playing_with_critic.py
  examples/ai_society/role_playing_with_human.py
  examples/external_tools/use_external_tools.py
  examples/function_call/code_execution.py
  examples/function_call/github_examples.py
  examples/function_call/openapi_function.py
  examples/function_call/role_playing_with_functions.py
  examples/generate_text_embedding_data/single_agent.py
  examples/generate_text_embedding_data/task_generation.py
  examples/misalignment/role_playing_multiprocess.py
  examples/misalignment/role_playing_with_human.py
  examples/models/azure_openai_model_example.py
  examples/models/role_playing_with_mistral.py
  examples/observability/agentops_track_roleplaying_with_function.py
  examples/structured_response/json_format_reponse_with_tools.py
  examples/translation/translator.py
  examples/vision/image_crafting.py
  examples/vision/multi_condition_image_crafting.py
  examples/vision/multi_turn_image_refining.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  pyproject.toml
  test/agents/test_chat_agent.py
  test/agents/test_role_playing.py
  test/models/test_litellm_model.py
  test/models/test_ollama_model.py
  test/models/test_open_source_model.py
  test/models/test_vllm_model.py
Labels: bug

#939 docs: Create prompting_templates.ipynb
  cookbooks/agents_prompting.ipynb
Labels: documentation

#818 docs：Add society doc
  docs/key_modules/society.md
Labels: documentation

#840 docs: add Camel docs - prompt
  docs/key_modules/prompt.md
Labels: documentation

#908 docs: Add memory cookbook
  cookbooks/agents_with_memory.ipynb
Labels: documentation

#811 docs: Add memory doc
  docs/key_modules/memory.md
Labels: documentation

#786 docs: add doc for workforce
  docs/key_modules/workforce.md
  poetry.lock
  test/workforce/test_single_agent.py
Labels: documentation

#790 docs: add doc for Tool
  docs/key_modules/tool.md
Labels: documentation

#792 docs: add doc for Task.
  docs/key_modules/task.md
Labels: documentation

#941 docs: models
  docs/key_modules/models.md
Labels: documentation

#914 docs: Add society cookbook
  cookbooks/agents_society.ipynb
Labels: documentation

#909 docs: Add message cookbook
  cookbooks/message_cookbook.ipynb
Labels: documentation

#891 feat: Simplify Tool setting
  camel/agents/chat_agent.py
  docs/tutorials_and_cookbooks/agents_with_tools.md
  docs/tutorials_and_cookbooks/agents_with_tools_from_Composio.md
  examples/function_call/code_execution.py
  examples/function_call/github_examples.py
  examples/function_call/openapi_function.py
  examples/function_call/role_playing_with_functions.py
  examples/models/role_playing_with_mistral.py
  examples/models/samba_model_example.py
  examples/observability/agentops_track_roleplaying_with_function.py
  examples/structured_response/json_format_reponse_with_tools.py
  examples/vision/image_crafting.py
  examples/vision/multi_condition_image_crafting.py
  examples/vision/multi_turn_image_refining.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  test/agents/test_chat_agent.py
  test/agents/test_role_playing.py
Labels: enhancement

#953 fix: Core module doc show table
  docs/README.md
  docs/camel.agents.rst
  docs/camel.configs.rst
  docs/camel.embeddings.rst
  docs/camel.interpreters.rst
  docs/camel.loaders.rst
  docs/camel.memories.blocks.rst
  docs/camel.memories.context_creators.rst
  docs/camel.memories.rst
  docs/camel.memory.rst
  docs/camel.messages.rst
  docs/camel.models.rst
  docs/camel.prompts.rst
  docs/camel.responses.rst
  docs/camel.retrievers.rst
  docs/camel.rst
  docs/camel.societies.rst
  docs/camel.storage.rst
  docs/camel.storages.graph_storages.rst
  docs/camel.storages.key_value_storages.rst
  docs/camel.storages.object_storages.rst
  docs/camel.storages.rst
  docs/camel.storages.vectordb_storages.rst
  docs/camel.tasks.rst
  docs/camel.terminators.rst
  docs/camel.toolkits.rst
  docs/camel.types.rst
  docs/camel.utils.rst
  docs/camel.workforce.rst
  docs/conf.py
  docs/index.rst
  docs/key_modules/models.md
  docs/key_modules/workforce.md
  poetry.lock
  pyproject.toml
Labels: documentation

#833 docs: Add colab notebooks
  docs/README.md
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/agents_with_tools_from_Composio.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/index.rst
  docs/tutorials_and_cookbooks/agents_with_rag.md
  docs/tutorials_and_cookbooks/agents_with_tools.md
  docs/tutorials_and_cookbooks/agents_with_tools_from_Composio.md
  examples/tasks/task_generation.py
  poetry.lock
  pyproject.toml
Labels: documentation

#954 fix: mock google api call
  test/toolkits/test_search_functions.py
Labels: enhancement

#956 feat: add pandoc for jupyter notebook doc
  .github/workflows/documentation.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#945 chore: reset and remove unsupported parameters in o1 model
  camel/models/openai_model.py
  camel/utils/token_counting.py
Labels: bug, enhancement, P0

#957 docs: update version and polish cookbooks
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/task_generation.ipynb
Labels: documentation

#877 Feat: workforce stable version
  camel/agents/chat_agent.py
  camel/tasks/task.py
  camel/tasks/task_prompt.py
  camel/utils/commons.py
  camel/workforce/__init__.py
  camel/workforce/base.py
  camel/workforce/manager_node.py
  camel/workforce/prompts.py
  camel/workforce/role_playing_node.py
  camel/workforce/role_playing_worker.py
  camel/workforce/single_agent_worker.py
  camel/workforce/task_channel.py
  camel/workforce/utils.py
  camel/workforce/worker.py
  camel/workforce/workforce.py
  camel/workforce/workforce_prompt.py
  examples/workforce/hackathon_judges.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  poetry.lock
  test/workforce/test_workforce_single_agent.py
Labels: enhancement

#963 docs: update cookbook with latest camel version
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/key_modules/models.md
Labels: documentation

#965 feat: llama model tool calling
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  docs/conf.py
  docs/get_started/setup.md
  examples/models/role_playing_with_sambanova.py
  pyproject.toml
Labels: Agent, Model

#968 feat: Nebula Graph integration
  camel/storages/__init__.py
  camel/storages/graph_storages/__init__.py
  camel/storages/graph_storages/nebula_graph.py
  examples/storages/nebular_graph.py
  poetry.lock
  pyproject.toml
  test/storages/graph_storages/test_nebula_graph.py
Labels: New Feature

#980 fix: unit test and mypy fails
  camel/configs/gemini_config.py
  poetry.lock
  test/toolkits/test_openai_function.py
Labels: bug

#981 docs: update the document of Workforce
  docs/key_modules/workforce.md
Labels: documentation

#976 docs: Add cookbook for workforce
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/agents_with_tools_from_Composio.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/index.rst
  poetry.lock
Labels: documentation

#974 chore: `RolePlaying` add warning for model setting
  camel/societies/role_playing.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#992 chore: update contribution guideline and poetry toml
  CONTRIBUTING.md
  camel/agents/chat_agent.py
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/key_modules/models.md
  examples/models/ollama_model_example.py
  examples/models/role_playing_with_sambanova.py
  poetry.lock
  pyproject.toml
Labels: documentation
