Repository camel-ai/camel, pull requests merged in 2024-03, with the labels that each got.

#475 [Bug] ToolAssistantToolsFunction can't find
  camel/functions/openai_function.py
  poetry.lock
  test/functions/test_openai_function.py
Labels: bug

#386 integrate Sentence Transformers for open source embedding models
  camel/embeddings/__init__.py
  camel/embeddings/base.py
  camel/embeddings/sentence_transformers_embeddings.py
  poetry.lock
  pyproject.toml
  test/embeddings/test_open_source_embeddings.py
Labels: New Feature, Embeddings

#456 feat: Integrate Milvus vector DB
  camel/storages/__init__.py
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/milvus.py
  poetry.lock
  pyproject.toml
  test/storages/vector_storages/test_milvus.py
Labels: New Feature

#482 feat: Milvus bump up to 2.4
  camel/storages/vectordb_storages/milvus.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#372 feat: deductive reasoner agent
  camel/agents/deductive_reasoner_agent.py
  examples/deductive_reasoner_agent/deduce_conditions_and_quality.py
  test/agents/test_deductive_reasoner_agent.py
Labels: Agent

#485 chore: update unstructured library dependency
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#467 feat: vector retriever
  camel/retrievers/__init__.py
  camel/retrievers/base.py
  camel/retrievers/vector_retriever.py
  camel/storages/vectordb_storages/base.py
  camel/storages/vectordb_storages/milvus.py
  camel/storages/vectordb_storages/qdrant.py
  test/retrievers/test_vector_retriever.py
Labels: New Feature

#469 feat: auto retriever
  camel/retrievers/__init__.py
  camel/retrievers/auto_retriever.py
  camel/types/__init__.py
  camel/types/enums.py
  test/retrievers/test_auto_retriever.py
Labels: New Feature

#492 [BUG] FunctionCallingMessage functions that have no arguments
  camel/messages/func_message.py
Labels: bug

#457 Add address description feature via Google Maps API
  camel/functions/__init__.py
  camel/functions/google_maps_function.py
  camel/utils/commons.py
  mypy
  poetry.lock
  pyproject.toml
  test/functions/test_google_maps_function.py
Labels: API, FunctionCall
