Repository camel-ai/camel, pull requests merged in 2024-07, with the labels that each got.

#649 feat: New open source models
  camel/types/enums.py
  camel/utils/token_counting.py
Labels: Model

#690 feat: Add utils to convert sync functions to async functions
  camel/utils/async_func.py
  test/agents/test_chat_agent.py
Labels: FunctionCall, New Feature

#696 refactor: Code with dependencies_required decorator
  camel/functions/search_functions.py
  camel/functions/slack_functions.py
  camel/functions/twitter_function.py
  camel/functions/weather_functions.py
  camel/loaders/base_io.py
  camel/loaders/unstructured_io.py
  camel/retrievers/bm25_retriever.py
  camel/retrievers/cohere_rerank_retriever.py
  camel/storages/graph_storages/neo4j_graph.py
  camel/storages/vectordb_storages/milvus.py
  camel/storages/vectordb_storages/qdrant.py
  camel/toolkits/github_toolkit.py
  examples/bots/discord_bot.py
  examples/bots/telegram_bot.py
Labels: Refactor

#656 feat: Integrate Jina Reader into loaders
  camel/loaders/__init__.py
  camel/loaders/jina_url_reader.py
  camel/types/enums.py
  examples/loaders/jina_url_reader_example.py
  test/loaders/test_jina_url_reader.py
Labels: New Feature, P0

#683 feat: add docker support of code execution
  camel/interpreters/__init__.py
  camel/interpreters/docker_interpreter.py
  camel/utils/__init__.py
  camel/utils/commons.py
  docs/key_modules/interpreters.md
  poetry.lock
  pyproject.toml
  test/interpreters/test_docker_interpreter.py
  test/utils/test_commons.py
Labels: New Feature

#710 chore: Add example for vlm embedding
  examples/embeddings/vlm_embedding_example.py
Labels: Example

#706 fix: update model calling for examples
  examples/ai_society/role_playing_multiprocess.py
  examples/ai_society/role_playing_with_critic.py
  examples/ai_society/role_playing_with_human.py
  examples/embeddings/vlm_embedding_example.py
  examples/function_call/role_playing_with_functions.py
  examples/generate_text_embedding_data/single_agent.py
  examples/generate_text_embedding_data/task_generation.py
  examples/misalignment/role_playing_multiprocess.py
  examples/misalignment/role_playing_with_human.py
  examples/misalignment/task_generation.py
  examples/vision/object_recognition.py
Labels: bug

#663 chore: Unify api decorator
  camel/embeddings/openai_embedding.py
  camel/models/anthropic_model.py
  camel/models/nemotron_model.py
  camel/models/openai_model.py
  camel/models/zhipuai_model.py
  camel/utils/__init__.py
  camel/utils/commons.py
  test/utils/test_commons.py
Labels: enhancement, P2

#689 feat: add install with docker compose support
  .container/.env.example
  .container/Dockerfile
  .container/README.md
  .container/docker-compose.yaml
  README.md
  poetry.lock
  pyproject.toml
Labels: New Feature

#711 release: v0.1.5.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: documentation, Release

#647 feat: Integrate Gemini 1.5
  camel/agents/task_agent.py
  camel/configs/__init__.py
  camel/configs/gemini_config.py
  camel/models/__init__.py
  camel/models/gemini_model.py
  camel/models/model_factory.py
  camel/types/enums.py
  camel/utils/__init__.py
  camel/utils/token_counting.py
  examples/models/gemini_model_example.py
  examples/models/role_playing_with_gemini.py
  poetry.lock
  pyproject.toml
  test/models/test_gemini_model.py
Labels: Model

#719 fix: model token_limit and gemini dependency
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/configs/gemini_config.py
  camel/models/base_model.py
  camel/models/litellm_model.py
  camel/models/ollama_model.py
  camel/models/zhipuai_model.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: bug

#749 feat: Add `GPT_4O_MINI`
  camel/agents/chat_agent.py
  camel/agents/critic_agent.py
  camel/agents/deductive_reasoner_agent.py
  camel/agents/embodied_agent.py
  camel/agents/knowledge_graph_agent.py
  camel/agents/role_assignment_agent.py
  camel/agents/search_agent.py
  camel/agents/task_agent.py
  camel/types/enums.py
  examples/vision/object_recognition.py
  test/agents/test_chat_agent.py
  test/agents/test_role_playing.py
  test/models/test_openai_model.py
Labels: Agent, Model

#736 fix: role playing with specific model
  examples/models/role_playing_with_claude.py
  examples/models/role_playing_with_gemini.py
  examples/models/role_playing_with_open_source_model.py
Labels: bug

#753 fix: n4j example
  camel/agents/chat_agent.py
  examples/knowledge_graph/knowledge_graph_agent_example.py
  examples/knowledge_graph/neo4j_example.py
Labels: bug

#777 release: V0.1.5.8
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  poetry.lock
  pyproject.toml
Labels: Release

#780 fix: Token number error for GPT3.5 turbo
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/retrievers/auto_retriever.py
  camel/types/enums.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: bug
