Repository camel-ai/camel, pull requests merged in 2024-10, with the labels that each got.

#1002 docs: Polish model setup doc for better onboarding experience
  camel/models/openai_compatibility_model.py
  docs/get_started/installation.md
  docs/get_started/setup.md
  docs/index.rst
  docs/key_modules/models.md
Labels: documentation

#1003 feat: Add support to handle bytes for vector retrieval
  camel/loaders/unstructured_io.py
  camel/retrievers/vector_retriever.py
Labels: enhancement, New Feature

#1011 feat: add cicd test for qa branch
  .github/workflows/build_package.yml
  .github/workflows/documentation.yml
  .github/workflows/pre_commit.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
Labels: enhancement

#1017 chore: mock duckduckgo search test
  test/toolkits/test_search_functions.py
Labels: enhancement

#1024 fix: vector retrieval type hint
  camel/loaders/unstructured_io.py
  camel/retrievers/vector_retriever.py
Labels: bug

#1016 feat: support mistral pixtral model
  camel/types/enums.py
  examples/models/mistral_model_example.py
  test/models/test_mistral_model.py
Labels: Model

#1037 fix: update test_func_message
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/installation.md
  pyproject.toml
  test/messages/test_func_message.py
Labels: bug

#1010 refactor: BaseModelBackend __init__ part
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/agents/chat_agent.py
  camel/models/anthropic_model.py
  camel/models/azure_openai_model.py
  camel/models/base_model.py
  camel/models/gemini_model.py
  camel/models/groq_model.py
  camel/models/litellm_model.py
  camel/models/mistral_model.py
  camel/models/model_factory.py
  camel/models/nemotron_model.py
  camel/models/ollama_model.py
  camel/models/open_source_model.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  camel/models/reka_model.py
  camel/models/samba_model.py
  camel/models/stub_model.py
  camel/models/togetherai_model.py
  camel/models/vllm_model.py
  camel/models/zhipuai_model.py
  docs/key_modules/prompts.md
  examples/models/azure_openai_model_example.py
  examples/models/role_playing_with_claude.py
  examples/models/role_playing_with_gemini.py
  examples/models/role_playing_with_groq.py
  examples/structured_response/json_format_response.py
  examples/test/test_ai_society_example.py
  examples/test/test_babyagi_example.py
  examples/test/test_code_example.py
  examples/test/test_role_description_example.py
  examples/test/test_single_agent.py
  examples/vision/image_crafting.py
  examples/vision/multi_condition_image_crafting.py
  examples/vision/multi_turn_image_refining.py
  examples/vision/object_recognition.py
  examples/vision/video_description.py
  examples/workforce/hackathon_judges.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  test/agents/test_babyagi_playing.py
  test/agents/test_chat_agent.py
  test/agents/test_role_playing.py
  test/agents/test_task_agent.py
  test/models/test_anthropic_model.py
  test/models/test_azure_openai_model.py
  test/models/test_litellm_model.py
  test/models/test_ollama_model.py
  test/models/test_openai_model.py
  test/models/test_reka_model.py
  test/models/test_samba_model.py
  test/models/test_togetherai_model.py
  test/models/test_vllm_model.py
  test/models/test_zhipuai_model.py
Labels: Refactor, Model

#1042 Remove Auto Assign of Issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/questions.yml
Labels: CI/CD

#1040 chore: refine CICD of publishing
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_release.yml
Labels: CI/CD

#966 feat: Refactor OpenAIFunction to FunctionTool
  camel/agents/chat_agent.py
  camel/configs/base_config.py
  camel/configs/groq_config.py
  camel/configs/openai_config.py
  camel/configs/samba_config.py
  camel/configs/zhipuai_config.py
  camel/messages/__init__.py
  camel/toolkits/__init__.py
  camel/toolkits/base.py
  camel/toolkits/code_execution.py
  camel/toolkits/dalle_toolkit.py
  camel/toolkits/function_tool.py
  camel/toolkits/github_toolkit.py
  camel/toolkits/google_maps_toolkit.py
  camel/toolkits/linkedin_toolkit.py
  camel/toolkits/math_toolkit.py
  camel/toolkits/open_api_toolkit.py
  camel/toolkits/reddit_toolkit.py
  camel/toolkits/retrieval_toolkit.py
  camel/toolkits/search_toolkit.py
  camel/toolkits/slack_toolkit.py
  camel/toolkits/twitter_toolkit.py
  camel/toolkits/weather_toolkit.py
  camel/utils/async_func.py
  docs/camel.toolkits.rst
  docs/key_modules/tools.md
  examples/function_call/github_examples.py
  examples/workforce/hackathon_judges.py
  examples/workforce/multiple_single_agents.py
  test/agents/test_chat_agent.py
  test/toolkits/test_openai_function.py
  test/toolkits/test_reddit_functions.py
Labels: enhancement, P0

#1038 feat: make system_message as optional
  camel/agents/chat_agent.py
  camel/societies/babyagi_playing.py
  camel/societies/role_playing.py
  test/agents/test_chat_agent.py
Labels: enhancement

#1057 docs: core module add link jump to cookbook
  docs/get_started/setup.md
  docs/index.rst
  docs/key_modules/memory.md
  docs/key_modules/models.md
  docs/key_modules/retrievers.md
  docs/key_modules/tasks.md
  docs/key_modules/tools.md
  docs/key_modules/workforce.md
Labels: documentation, enhancement

#994 feat: add arxiv toolkit
  camel/toolkits/__init__.py
  camel/toolkits/arxiv_toolkit.py
  camel/toolkits/base.py
  camel/toolkits/code_execution.py
  camel/toolkits/github_toolkit.py
  examples/tool_call/arxiv_toolkit_example.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_arxiv_functions.py
Labels: New Feature

#997 feat: Google scholar toolkit
  camel/toolkits/__init__.py
  camel/toolkits/arxiv_toolkit.py
  camel/toolkits/google_scholar_toolkit.py
  examples/test/test_ai_society_example.py
  examples/tool_call/code_execution_toolkit.py
  examples/tool_call/github_toolkit.py
  examples/tool_call/google_scholar_toolkit.py
  examples/tool_call/openapi_toolkit.py
  examples/tool_call/reddit_examples.py
  examples/tool_call/role_playing_with_functions.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_google_scholar_toolkit.py
Labels: New Feature

#884 feat: add AskNews toolkit
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/toolkits/__init__.py
  camel/toolkits/ask_news_toolkit.py
  examples/tool_call/ask_news_toolkit_example.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_asknews_function.py
Labels: New Feature

#1067 chore: update dependency toml
  poetry.lock
  pyproject.toml
Labels: enhancement

#1068 chore: Rename `model` to `model_type` in `ModelFactory`
  camel/models/model_factory.py
Labels: Model

#972 feat: Integrate What's App
  camel/toolkits/whatsapp_toolkit.py
  camel/utils/commons.py
  test/toolkits/test_whatsapp_function.py
Labels: New Feature

#1076 feat: add ministral 3b and 8b and some small enhancements
  camel/agents/chat_agent.py
  camel/configs/anthropic_config.py
  camel/configs/groq_config.py
  camel/configs/ollama_config.py
  camel/configs/openai_config.py
  camel/configs/samba_config.py
  camel/configs/togetherai_config.py
  camel/configs/vllm_config.py
  camel/configs/zhipuai_config.py
  camel/embeddings/openai_embedding.py
  camel/loaders/firecrawl_reader.py
  camel/models/anthropic_model.py
  camel/models/gemini_model.py
  camel/models/litellm_model.py
  camel/models/mistral_model.py
  camel/models/reka_model.py
  camel/types/__init__.py
  camel/types/enums.py
  camel/types/openai_types.py
  camel/utils/token_counting.py
  camel/workforce/role_playing_worker.py
  camel/workforce/single_agent_worker.py
  camel/workforce/workforce.py
  docs/key_modules/models.md
  examples/loaders/firecrawl_example.py
  examples/models/mistral_model_example.py
  examples/structured_response/json_format_reponse_with_tools.py
  examples/structured_response/json_format_response.py
  poetry.lock
  pyproject.toml
  test/agents/test_chat_agent.py
  test/loaders/test_firecrawl.py
Labels: enhancement

#1071 fix: unify token_limit property
  camel/models/base_model.py
  camel/models/litellm_model.py
  camel/models/ollama_model.py
  camel/models/openai_compatible_model.py
  camel/models/samba_model.py
  camel/models/togetherai_model.py
  camel/models/vllm_model.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/openai_compatibility_model_examples/nemotron.py
Labels: bug

#1091 Docs: Typo Fix
  README.md
Labels: documentation

#1089 chore: update CI/CD
  .github/workflows/publish_release.yml
Labels: CI/CD

#1087 refactor: twitter toolkit
  camel/toolkits/__init__.py
  camel/toolkits/twitter_toolkit.py
  camel/utils/commons.py
  examples/toolkits/post_weather_on_twitter.py
  poetry.lock
  test/toolkits/test_twitter_function.py
Labels: Refactor

#1095 chore: update `readme`, `discord`, `license`
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/index.rst
  licenses/DATA_LICENSE
Labels: Readme

#1096 Small fix on `readme.md`
  README.md
Labels: Readme

#1085 fix: `validate_openai_tool_schema`
  camel/toolkits/function_tool.py
  test/toolkits/test_openai_function.py
Labels: FunctionCall

#1105 docs: first agent doc and readme update
  README.md
  docs/cookbooks/create_your_first_agent.ipynb
Labels: documentation

#1102 docs: model speed
  camel/workforce/task_channel.py
  docs/camel.workforce.rst
  docs/cookbooks/model_speed_comparison.ipynb
  docs/index.rst
  docs/key_modules/models.md
Labels: documentation

#1109 feat: Agentops support for SambaNova
  camel/loaders/chunkr_reader.py
  camel/models/samba_model.py
  examples/models/role_playing_with_sambanova.py
Labels: New Feature

#1082 fix: support python 3.12
  README.md
  camel/agents/knowledge_graph_agent.py
  camel/loaders/unstructured_io.py
  camel/retrievers/auto_retriever.py
  camel/retrievers/vector_retriever.py
  camel/storages/graph_storages/graph_element.py
  examples/bots/discord_bot.py
  examples/bots/discord_bot_use_msg_queue.py
  examples/bots/slack_bot.py
  examples/bots/slack_bot_use_msg_queue.py
  examples/test/test_unstructured_io_example.py
  poetry.lock
  pyproject.toml
  test/loaders/test_unstructured_io.py
  test/retrievers/test_vector_retriever.py
Labels: bug

#1101 feat: ChatAgent interface enhancement and default model setting
  camel/agents/chat_agent.py
  camel/types/enums.py
  camel/workforce/workforce.py
  examples/ai_society/role_playing_multiprocess.py
  examples/ai_society/role_playing_with_critic.py
  examples/ai_society/role_playing_with_human.py
  examples/external_tools/use_external_tools.py
  examples/generate_text_embedding_data/single_agent.py
  examples/generate_text_embedding_data/task_generation.py
  examples/misalignment/role_playing_multiprocess.py
  examples/misalignment/role_playing_with_human.py
  examples/observability/agentops_track_roleplaying_with_function.py
  examples/structured_response/json_format_reponse_with_tools.py
  examples/structured_response/json_format_response.py
  examples/tasks/task_generation.py
  examples/tool_call/arxiv_toolkit_example.py
  examples/tool_call/code_execution_toolkit.py
  examples/tool_call/github_toolkit.py
  examples/tool_call/google_scholar_toolkit.py
  examples/tool_call/openapi_toolkit.py
  examples/tool_call/role_playing_with_functions.py
  examples/translation/translator.py
  examples/vision/image_crafting.py
  examples/vision/multi_condition_image_crafting.py
  examples/vision/multi_turn_image_refining.py
  examples/vision/object_recognition.py
  examples/vision/video_description.py
  examples/workforce/hackathon_judges.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  test/agents/test_chat_agent.py
Labels: enhancement

#1113 fix: graph element
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/storages/graph_storages/graph_element.py
  docs/conf.py
  docs/get_started/installation.md
  poetry.lock
  pyproject.toml
  test/storages/graph_storages/test_graph_element.py
Labels: bug

#1114 fix: remove file modify check for auto retriever
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/retrievers/auto_retriever.py
  docs/conf.py
  docs/get_started/installation.md
  poetry.lock
  pyproject.toml
Labels: bug

#1116 docs: update core modules part
  camel/toolkits/dalle_toolkit.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/key_modules/embeddings.md
  docs/key_modules/messages.md
  docs/key_modules/models.md
  docs/key_modules/retrievers.md
  docs/key_modules/society.md
  docs/key_modules/storages.md
  docs/key_modules/tasks.md
  docs/key_modules/tools.md
  misc/logo_dark.png
Labels: documentation

#1117 chore: move workforce under society & small doc polish
  camel/societies/workforce/__init__.py
  camel/societies/workforce/base.py
  camel/societies/workforce/prompts.py
  camel/societies/workforce/role_playing_worker.py
  camel/societies/workforce/single_agent_worker.py
  camel/societies/workforce/task_channel.py
  camel/societies/workforce/utils.py
  camel/societies/workforce/worker.py
  camel/societies/workforce/workforce.py
  docs/camel.rst
  docs/camel.societies.rst
  docs/camel.societies.workforce.rst
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  examples/workforce/hackathon_judges.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  poetry.lock
  test/workforce/test_workforce_single_agent.py
Labels: enhancement

#1118 fix: Remove orig_elements in unstructured element metadata
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/retrievers/vector_retriever.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/workforce.md
  pyproject.toml
Labels: bug, enhancement

#1120 fix: llama tool call msg & remove samba fast api
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/configs/__init__.py
  camel/configs/samba_config.py
  camel/models/samba_model.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  examples/models/samba_model_example.py
  poetry.lock
  pyproject.toml
Labels: bug

#1111 feat: Notion toolkit integration
  camel/toolkits/__init__.py
  camel/toolkits/notion_toolkit.py
  examples/tool_call/google_scholar_toolkit.py
  examples/tool_call/notion_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_notion_toolkit.py
Labels: New Feature

#1124 feat: google scholar toolkit support `author` assignment
  camel/toolkits/google_scholar_toolkit.py
Labels: enhancement

#1123 feat: Integrate apify
  camel/loaders/__init__.py
  camel/loaders/apify_reader.py
  examples/loaders/apify_example.py
  poetry.lock
  pyproject.toml
  test/loaders/test_apify.py
Labels: New Feature

#1039 feat: Tavily search integration
  camel/toolkits/search_toolkit.py
  poetry.lock
  pyproject.toml
Labels: New Feature

#1070 feat: generate openai tool schema
  camel/toolkits/__init__.py
  camel/toolkits/function_tool.py
  examples/test/test_ai_society_example.py
  examples/toolkits/arxiv_toolkit.py
  examples/toolkits/ask_news_toolkit.py
  examples/toolkits/code_execution_toolkit.py
  examples/toolkits/generate_openai_tool_schema.py
  examples/toolkits/github_toolkit.py
  examples/toolkits/google_scholar_toolkit.py
  examples/toolkits/notion_toolkit.py
  examples/toolkits/openapi_toolkit.py
  examples/toolkits/reddit_toolkit.py
  examples/toolkits/role_playing_with_functions.py
  test/agents/test_chat_agent.py
  test/toolkits/test_generate_openai_tool_schema.py
Labels: New Feature

#979 feat: Add data commons toolkit
  camel/toolkits/data_commons_toolkit.py
  examples/toolkits/data_commons_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_data_commons_toolkit.py
Labels: New Feature

#1138 chore: add grok example
  examples/models/openai_compatibility_model_examples/grok.py
Labels: Model
