Repository camel-ai/camel, pull requests merged in 2024-05, with the labels that each got.

#538 fix: errors in task_generation examples
  examples/misalignment/task_generation.py
Labels: bug

#471 feat: cohere rerank retriever
  .github/workflows/build_package.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  camel/retrievers/__init__.py
  camel/retrievers/cohere_rerank_retriever.py
  poetry.lock
  pyproject.toml
  test/retrievers/test_cohere_rerank_retriever.py
Labels: New Feature

#540 Add `configs` folder
  camel/configs/__init__.py
  camel/configs/anthropic_config.py
  camel/configs/base_config.py
  camel/configs/openai_config.py
Labels: enhancement, Model

#539 Remove `ChatGPTVisionConfig` and refactor configs
  camel/agents/chat_agent.py
  camel/configs/__init__.py
  camel/configs/anthropic_config.py
  camel/configs/base_config.py
  camel/configs/openai_config.py
  camel/types/enums.py
  examples/vision/object_recognition.py
  test/agents/test_chat_agent.py
  test/models/test_openai_model.py
Labels: enhancement, Agent

#555 feat: add gpt4o
  camel/types/enums.py
  poetry.lock
  pyproject.toml
  test/models/test_openai_model.py
Labels: New Feature

#537 feat: RAG citation and function call
  camel/functions/__init__.py
  camel/functions/retrieval_functions.py
  camel/retrievers/auto_retriever.py
  camel/retrievers/vector_retriever.py
  test/storages/graph_storages/test_neo4j_graph.py
Labels: enhancement, New Feature

#559 feat: Add GitHub integration
  camel/toolkits/__init__.py
  camel/toolkits/base.py
  camel/toolkits/github_toolkit.py
  examples/function_call/github_examples.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_github_toolkit.py
Labels: New Feature

#566 feat: knowledge graph agent
  camel/agents/__init__.py
  camel/agents/knowledge_graph_agent.py
  examples/knowledge_graph/knowledge_graph_agent.py
  examples/knowledge_graph/neo4j.py
  test/agents/test_knowledge_agent.py
Labels: Agent

#561 feat: Integrate OpenAI audio models
  camel/models/__init__.py
  camel/models/openai_audio_models.py
  camel/types/__init__.py
  camel/types/enums.py
  examples/openai_audio_models/openai_audio_models.py
  poetry.lock
  pyproject.toml
  test/models/test_openai_audio_models.py
Labels: Model, New Feature

#560 feat: Integrate slack
  camel/functions/__init__.py
  camel/functions/slack_functions.py
  poetry.lock
  pyproject.toml
  test/functions/test_slack_functions.py
Labels: New Feature

#556 refactor: move from function to tools
  camel/agents/chat_agent.py
  camel/configs/__init__.py
  camel/configs/openai_config.py
  camel/functions/openai_function.py
  camel/models/openai_model.py
  camel/utils/commons.py
  docs/agents/single_agent.md
  docs/tutorials_and_cookbooks/agents_with_rag.md
  test/agents/test_chat_agent.py
  test/agents/test_role_playing.py
  test/models/test_open_source_model.py
Labels: Refactor

#551 feat: ChatAgent support api key as parameter
  camel/agents/chat_agent.py
  camel/embeddings/openai_embedding.py
  camel/models/anthropic_model.py
  camel/models/base_model.py
  camel/models/model_factory.py
  camel/models/openai_model.py
  camel/models/stub_model.py
  camel/utils/commons.py
Labels: enhancement

#405 [Feature] Add dependencies_required and api_keys_required
  camel/utils/__init__.py
  camel/utils/commons.py
  test/utils/test_commons.py
Labels: size:L

#549 chores: move `role_playing_with_functions` from utils into example
  camel/utils/__init__.py
  camel/utils/commons.py
  examples/function_call/github_examples.py
  examples/function_call/role_playing_with_function.py
  examples/function_call/role_playing_with_functions.py
  examples/test/test_ai_society_example.py
Labels: enhancement

#597 release: version 0.1.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release

#598 release: v0.1.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release
