Repository camel-ai/camel, pull requests merged in 2024-04, with the labels that each got.

#494 Add Wolfram|Alpha Query Feature via search_wolfram_alpha api
  camel/functions/search_functions.py
  poetry.lock
  pyproject.toml
  test/functions/test_search_functions.py
Labels: API, FunctionCall

#470 feat: bm25 retriever
  camel/retrievers/__init__.py
  camel/retrievers/base.py
  camel/retrievers/bm25_retriever.py
  camel/retrievers/vector_retriever.py
  camel/utils/commons.py
  mypy
  poetry.lock
  pyproject.toml
  test/retrievers/test_bm25_retriever.py
  test/retrievers/test_vector_retriever.py
Labels: New Feature

#473 feat: enable image modality for `ChatAgent`
  camel/agents/chat_agent.py
  camel/configs.py
  camel/memories/context_creators/score_based.py
  camel/messages/base.py
  camel/prompts/__init__.py
  camel/prompts/object_recognition.py
  camel/prompts/task_prompt_template.py
  camel/types/__init__.py
  camel/types/enums.py
  camel/utils/token_counting.py
  examples/vision/object_recognition.py
  test/agents/test_chat_agent.py
  test/utils/test_token_counting.py
Labels: Agent, Prompt, Example, New Feature

#513 [BUG] duplicated documentation for agent
  CONTRIBUTING.md
  README.md
  docs/agents/chat_agents.md
  docs/agents/role_playing.md
  docs/get_started/setup.md
  docs/index.rst
  docs/key_modules/loaders.md
  docs/key_modules/retrievers.md
  docs/key_modules/storages.md
  docs/tutorials_and_cookbooks/agents_with_rag.md
Labels: bug, documentation

#530 fix/update to qdrant 1.9 version
  camel/storages/vectordb_storages/qdrant.py
  poetry.lock
  pyproject.toml
Labels: bug

#511 Update `ModelType` and remove legacy models
  camel/types/enums.py
  test/agents/test_role_playing.py
  test/models/test_openai_model.py
Labels: Model

#516 feat: add create_element_from_text to Unstructured IO module
  camel/loaders/unstructured_io.py
  test/loaders/test_unstructured_io.py
Labels: enhancement

#517 feat: Enable Twitter API Function Calls for Social Media Interactions
  camel/functions/__init__.py
  camel/functions/twitter_function.py
  camel/utils/commons.py
  poetry.lock
  pyproject.toml
  test/functions/test_twitter_function.py
Labels: enhancement, API, FunctionCall, New Feature
