Repository camel-ai/camel, pull requests merged in 2024-12, with the labels that each got.

#1258 fix: use print instead of customized logger for human tool
  camel/toolkits/human_toolkit.py
Labels: bug

#1268 fix: Remove deprecated `min_tokens` parameter from mistral config.
  camel/configs/mistral_config.py
Labels: bug, Model

#1202 feat: Alpaca pydantic class for easy conversion, validation, and structured output generation
  camel/messages/__init__.py
  camel/messages/conversion/__init__.py
  camel/messages/conversion/alpaca.py
  camel/messages/conversion/conversation_models.py
Labels: New Feature

#1226 feat: add NVIDIA model platform support
  .env
  camel/configs/__init__.py
  camel/configs/nvidia_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/nvidia_model.py
  camel/types/enums.py
  docs/key_modules/models.md
  examples/models/nemotron_model_example.py
  examples/models/nvidia_model_example.py
  test/models/test_nvidia_model.py
Labels: Model

#1229 feat: support openai structured output as objecct
  camel/agents/chat_agent.py
  camel/messages/base.py
  camel/models/openai_model.py
  examples/models/openai_structured_output_example.py
Labels: Message, Model

#701 feat: Add logging
  apps/agents/agents.py
  apps/data_explorer/data_explorer.py
  apps/data_explorer/downloader.py
  apps/dilemma/database_connection.py
  apps/dilemma/dilemma.py
  camel/__init__.py
  camel/agents/deductive_reasoner_agent.py
  camel/embeddings/vlm_embedding.py
  camel/interpreters/docker_interpreter.py
  camel/interpreters/subprocess_interpreter.py
  camel/logger.py
  camel/societies/babyagi_playing.py
  camel/toolkits/twitter_toolkit.py
  camel/utils/commons.py
  camel/utils/token_counting.py
Labels: New Feature

#1234 feat: Integrate Brave Web Search API in search toolkit (#1005)
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
Labels: New Feature

#1285 docs: add customer_service_Discord_bot_with_agentic_RAG
  README.md
  docs/cookbooks/customer_service_Discord_bot_with_agentic_RAG.ipynb
  docs/index.rst
Labels: documentation

#1292 docs: add sft_data_generation_and_unsloth_finetuning with other models
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning.ipynb
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning_Qwen2_5_7B.ipynb
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning_mistral_7b_instruct.ipynb
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning_tinyllama.ipynb
  docs/index.rst
Labels: documentation

#1181 feat: Add GAIA benchmark
  camel/benchmarks/__init__.py
  camel/benchmarks/base.py
  camel/benchmarks/gaia.py
  camel/toolkits/math_toolkit.py
  camel/toolkits/search_toolkit.py
  examples/benchmarks/gaia.py
  examples/benchmarks/gaia_results.jsonl
  poetry.lock
  test/agents/test_chat_agent.py
  test/benchmarks/test_gaia_benchmark.py
Labels: Evaluation

#1294 docs: add customer_service_Discord_bot_using_SambaNova_with_agentic_RAG
  docs/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.ipynb
  docs/index.rst
Labels: documentation

#1239 feature request pipeline to fetch upload data to hugging face
  camel/datahubs/__init__.py
  camel/datahubs/base.py
  camel/datahubs/huggingface.py
  camel/datahubs/models.py
  camel/types/__init__.py
  camel/types/enums.py
  examples/datahubs/huggingface.py
  poetry.lock
  pyproject.toml
  test/datahubs/test_huggingface.py
Labels: Data

#1304 docs: update customer_service_Discord_bot_using_SambaNova_with_agenti…
  docs/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.ipynb
Labels: documentation

#1306 feat: Add llama3.3_70B model
  camel/models/groq_model.py
  camel/types/enums.py
  examples/models/groq_model_example.py
  examples/models/nvidia_model_example.py
Labels: Model

#1310 fix: outdated code snippets for loaders module in doc
  .gitignore
  camel/loaders/__init__.py
  camel/loaders/base_io.py
  camel/storages/object_storages/amazon_s3.py
  camel/storages/object_storages/azure_blob.py
  camel/storages/object_storages/google_cloud.py
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
  test/loaders/test_base_io.py
Labels: bug

#1305 feat: support ollama.com structured-outputs Support ollama structured output.
  camel/configs/ollama_config.py
  camel/models/base_model.py
  camel/models/ollama_model.py
  camel/models/openai_model.py
  examples/models/ollama_model_example.py
Labels: Model

#1271 feat: Reward model
  camel/models/reward/__init__.py
  camel/models/reward/base_reward_model.py
  camel/models/reward/evaluator.py
  camel/models/reward/nemetro_model.py
  examples/reward/nemotron_model_example.py
  test/models/reward/test_nemetro_model.py
Labels: Model

#1255 feat: integrate sglang in camel
  camel/configs/__init__.py
  camel/configs/sglang_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/sglang_model.py
  camel/types/enums.py
  examples/models/sglang_model_example.py
  poetry.lock
  pyproject.toml
  test/models/test_sglang_model.py
Labels: Model

#1261 feat: Integrate stripe
  camel/toolkits/__init__.py
  camel/toolkits/stripe_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_stripe_function.py
Labels: New Feature

#1311 chore: Update some versions
  camel/models/anthropic_model.py
  camel/models/vllm_model.py
  camel/types/enums.py
  camel/utils/token_counting.py
  docs/key_modules/models.md
  examples/models/vllm_model_example.py
  poetry.lock
  pyproject.toml
  test/models/test_anthropic_model.py
Labels: bug

#1284 feat: Integrate e2b.
  camel/interpreters/__init__.py
  camel/interpreters/e2b_interpreter.py
  camel/toolkits/code_execution.py
  docs/key_modules/interpreters.md
  examples/toolkits/code_execution_toolkit.py
  poetry.lock
  pyproject.toml
Labels: New Feature

#1193 feat: add data collector for dataset generation
  camel/data_collector/__init__.py
  camel/data_collector/alpaca_collector.py
  camel/data_collector/base.py
  camel/data_collector/sharegpt_collector.py
  camel/messages/__init__.py
  camel/schemas/openai_converter.py
  examples/data_collector/alpaca_collector.py
  examples/data_collector/sharegpt_collector.py
  test/data_collectors/test_alpaca_collector.py
  test/data_collectors/test_sharegpt_collector.py
Labels: Data

#1206 feat: set structured output from ChatAgent using openai beta client
  camel/agents/chat_agent.py
  camel/personas/persona_hub.py
  camel/societies/workforce/role_playing_worker.py
  camel/societies/workforce/single_agent_worker.py
  camel/societies/workforce/workforce.py
  camel/toolkits/function_tool.py
  examples/models/openai_structured_output_example.py
  poetry.lock
  test/agents/test_chat_agent.py
  test/toolkits/test_generate_openai_tool_schema.py
  test/toolkits/test_openai_function.py
  test/toolkits/test_synthesize_output.py
Labels: Agent

#1320 chore: new version release and test fix
  .env
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.ipynb
  docs/cookbooks/customer_service_Discord_bot_with_agentic_RAG.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
  test/data_collectors/test_sharegpt_collector.py
  test/loaders/test_unstructured_io.py
Labels: bug

#1128 chore: Add mock LLM for test purposes; Enable multiple `step()` calls in test units to enhance test robustness
  test/agents/test_babyagi_playing.py
  test/agents/test_chat_agent.py
  test/agents/test_embodied_agent.py
  test/agents/test_role_playing.py
  test/agents/tool_agents/test_hugging_face_tool_agent.py
Labels: Test

#1335 feat: increate timeout for LLMs, release new version
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/embeddings/openai_compatible_embedding.py
  camel/embeddings/openai_embedding.py
  camel/models/azure_openai_model.py
  camel/models/deepseek_model.py
  camel/models/gemini_model.py
  camel/models/groq_model.py
  camel/models/nemotron_model.py
  camel/models/nvidia_model.py
  camel/models/ollama_model.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  camel/models/qwen_model.py
  camel/models/reward/nemotron_model.py
  camel/models/samba_model.py
  camel/models/sglang_model.py
  camel/models/togetherai_model.py
  camel/models/vllm_model.py
  camel/models/yi_model.py
  camel/models/zhipuai_model.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.ipynb
  docs/cookbooks/customer_service_Discord_bot_with_agentic_RAG.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#1287 feat: Integrate fish audio
  camel/agents/chat_agent.py
  camel/messages/base.py
  camel/models/__init__.py
  camel/models/anthropic_model.py
  camel/models/fish_audio_model.py
  camel/runtime/configs.py
  camel/runtime/docker_runtime.py
  camel/runtime/llm_guard_runtime.py
  camel/runtime/remote_http_runtime.py
  camel/runtime/utils/function_risk_toolkit.py
  camel/runtime/utils/ignore_risk_toolkit.py
  camel/toolkits/arxiv_toolkit.py
  camel/toolkits/ask_news_toolkit.py
  camel/toolkits/github_toolkit.py
  camel/toolkits/meshy_toolkit.py
  camel/toolkits/search_toolkit.py
  examples/models/fish_audio_model_example.py
  poetry.lock
  pyproject.toml
  test/models/test_fish_audio_model.py
Labels: Model

#1318 feat: Implement outlines converter model for structured output (#1211)
  camel/schemas/__init__.py
  camel/schemas/base.py
  camel/schemas/outlines_converter.py
  examples/schema_outputs/outlines_converter_example.py
  poetry.lock
  pyproject.toml
Labels: New Feature

#1337 docs: add cookbook contribution guideline
  CONTRIBUTING.md
Labels: documentation

#1340 feat: Support OpenAI O1 model
  camel/models/openai_model.py
  camel/types/enums.py
  camel/utils/token_counting.py
  docs/key_modules/models.md
  examples/models/openai_o1_example.py
  poetry.lock
  pyproject.toml
  test/models/test_openai_model.py
Labels: Model

#1346 release: Version 0.2.14
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.ipynb
  docs/cookbooks/customer_service_Discord_bot_with_agentic_RAG.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
Labels: Release

#1142 feat: `ChatAgent` refactoring
  camel/agents/chat_agent.py
  camel/societies/role_playing.py
  camel/societies/workforce/workforce.py
  camel/types/enums.py
  camel/utils/__init__.py
  camel/utils/commons.py
  examples/structured_response/structure_response_prompt_engineering.py
  test/agents/test_chat_agent.py
Labels: enhancement, New Feature

#1354 feat: add native structure output property
  camel/agents/chat_agent.py
  camel/retrievers/vector_retriever.py
  camel/storages/graph_storages/nebula_graph.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  poetry.lock
  pyproject.toml
  test/storages/graph_storages/test_nebula_graph.py
Labels: New Feature

#1276 feat: Preliminary implementation of self-instruct pipeline
  camel/synthetic_datagen/__init__.py
  camel/synthetic_datagen/self_instruct/__init__.py
  camel/synthetic_datagen/self_instruct/filter/__init__.py
  camel/synthetic_datagen/self_instruct/filter/filter_function.py
  camel/synthetic_datagen/self_instruct/filter/filter_registry.py
  camel/synthetic_datagen/self_instruct/filter/instruction_filter.py
  camel/synthetic_datagen/self_instruct/self_instruct.py
  camel/synthetic_datagen/self_instruct/templates.py
  examples/synthetic_datagen/self_instruct/data_output.json
  examples/synthetic_datagen/self_instruct/seed_tasks.jsonl
  examples/synthetic_datagen/self_instruct/self_instruct.py
  poetry.lock
  pyproject.toml
  test/synthetic_datagen/self_instruct/filter/filter_function_tests.py
  test/synthetic_datagen/self_instruct/filter/instruction_filter_tests.py
  test/synthetic_datagen/self_instruct/self_instruct_tests.py
Labels: New Feature

#1359 docs：add o1datagene_cookbook
  README.md
  docs/cookbooks/O1datagen_with_CAMEL_And_Upload_Data_To_Huggingface.ipynb
  docs/index.rst
Labels: documentation, Data

#1363 fix: Changed params format in markdown_crawl
  camel/loaders/firecrawl_reader.py
  test/loaders/test_firecrawl.py
Labels: bug

#1288 docs: o1datagen_sft_qwen_with_unsolth_upload_to_hf with CAMEL
  README.md
  docs/cookbooks/O1datagen_with_CAMEL_And_Sft_Qwen_With_Unsolth_And_Upload_Data_And_Model_To_Huggingface.ipynb
  docs/index.rst
Labels: Data

#1362 fix: Add Error Handling for Arxiv to Text
  camel/toolkits/arxiv_toolkit.py
Labels: bug

#1307 docs: Added discord bot with agentic RAG supports local model
  README.md
  docs/cookbooks/customer_service_Discord_bot_using_local_model_with_agentic_RAG.ipynb
  docs/index.rst
Labels: documentation

#766 feat: Graph sampling with Neo4j
  camel/storages/graph_storages/neo4j_graph.py
  test/storages/graph_storages/test_neo4j_graph.py
Labels: New Feature

#1368 feat: Linkup intergrate
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_search_functions.py
Labels: New Feature

#1370 fix: enhancment for tool benchmark integration
  camel/benchmarks/__init__.py
  camel/benchmarks/apibank.py
  camel/benchmarks/apibench.py
  camel/benchmarks/gaia.py
  camel/benchmarks/nexus.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1277 fix: api_keys_required
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/datahubs/huggingface.py
  camel/embeddings/mistral_embedding.py
  camel/embeddings/openai_compatible_embedding.py
  camel/embeddings/openai_embedding.py
  camel/interpreters/e2b_interpreter.py
  camel/loaders/apify_reader.py
  camel/loaders/chunkr_reader.py
  camel/logger.py
  camel/models/anthropic_model.py
  camel/models/azure_openai_model.py
  camel/models/cohere_model.py
  camel/models/deepseek_model.py
  camel/models/gemini_model.py
  camel/models/groq_model.py
  camel/models/mistral_model.py
  camel/models/nemotron_model.py
  camel/models/nvidia_model.py
  camel/models/openai_model.py
  camel/models/qwen_model.py
  camel/models/reka_model.py
  camel/models/reward/nemotron_model.py
  camel/models/samba_model.py
  camel/models/togetherai_model.py
  camel/models/yi_model.py
  camel/models/zhipuai_model.py
  camel/schemas/openai_converter.py
  camel/toolkits/meshy_toolkit.py
  camel/toolkits/search_toolkit.py
  camel/toolkits/stripe_toolkit.py
  camel/toolkits/twitter_toolkit.py
  camel/utils/commons.py
  test/utils/test_commons.py
Labels: bug

#1372 docs: cited self-instruct paper
  README.md
  camel/datagen/__init__.py
  camel/datagen/self_instruct/__init__.py
  camel/datagen/self_instruct/filter/__init__.py
  camel/datagen/self_instruct/filter/filter_function.py
  camel/datagen/self_instruct/filter/filter_registry.py
  camel/datagen/self_instruct/filter/instruction_filter.py
  camel/datagen/self_instruct/self_instruct.py
  camel/datagen/self_instruct/templates.py
  camel/synthetic_datagen/__init__.py
  camel/toolkits/search_toolkit.py
  examples/synthetic_datagen/self_instruct/self_instruct.py
  test/datagen/self_instruct/filter/filter_function_tests.py
  test/datagen/self_instruct/filter/instruction_filter_tests.py
  test/datagen/self_instruct/self_instruct_tests.py
Labels: documentation
