Repository camel-ai/camel, pull requests merged in 2024-08, with the labels that each got.

#781 feat: Integrate firecrawl
  camel/loaders/__init__.py
  camel/loaders/firecrawl_reader.py
  examples/loaders/firecrawl_example.py
  poetry.lock
  pyproject.toml
  test/loaders/test_firecrawl.py
Labels: New Feature

#763 docs: Add tool cookbook including Composio
  docs/tutorials_and_cookbooks/agents_with_rag.md
  docs/tutorials_and_cookbooks/agents_with_tools.md
  docs/tutorials_and_cookbooks/agents_with_tools_from_Composio.md
  pyproject.toml
Labels: documentation

#699 feat: `Task` in camel
  camel/tasks/__init__.py
  camel/tasks/task.py
  camel/tasks/task_prompt.py
  examples/tasks/task_generation.py
  poetry.lock
  test/tasks/test_task.py
Labels: New Feature

#698 feat: Support multi-modal input and multi-modal output in one agent Dalle support
  camel/messages/base.py
  camel/prompts/__init__.py
  camel/prompts/image_craft.py
  camel/prompts/multi_condition_image_craft.py
  camel/prompts/task_prompt_template.py
  camel/toolkits/__init__.py
  camel/toolkits/dalle_toolkit.py
  camel/types/enums.py
  examples/vision/image_crafting.py
  examples/vision/multi_condition_image_crafting.py
  examples/vision/multi_turn_image_refining.py
  examples/vision/object_recognition.py
  test/toolkits/test_dalle_functions.py
Labels: New Feature

#778 feat: structure response using function call
  camel/agents/chat_agent.py
  camel/agents/embodied_agent.py
  camel/toolkits/google_maps_toolkit.py
  camel/toolkits/openai_function.py
  camel/utils/__init__.py
  camel/utils/commons.py
  camel/utils/constants.py
  examples/structured_response/json_format_reponse_with_tools.py
  examples/structured_response/json_format_response.py
  test/agents/test_chat_agent.py
  test/toolkits/test_openai_function.py
Labels: New Feature

#789 fix: align with pydantic update
  camel/agents/chat_agent.py
  docs/tutorials_and_cookbooks/agents_with_tools.md
  docs/tutorials_and_cookbooks/agents_with_tools_from_Composio.md
  examples/models/mistral_model_example.py
  examples/structured_response/json_format_reponse_with_tools.py
  examples/structured_response/json_format_response.py
  examples/tasks/task_generation.py
  examples/vision/image_crafting.py
  examples/vision/multi_condition_image_crafting.py
  examples/vision/multi_turn_image_refining.py
Labels: bug

#713 feat: Add Workforce
  camel/tasks/task.py
  camel/workforce/__init__.py
  camel/workforce/base.py
  camel/workforce/manager_node.py
  camel/workforce/role_playing_node.py
  camel/workforce/single_agent_node.py
  camel/workforce/task_channel.py
  camel/workforce/utils.py
  camel/workforce/worker_node.py
  camel/workforce/workforce.py
  camel/workforce/workforce_prompt.py
  examples/workforce/multiple_single_agents.py
  examples/workforce/role_playing_with_agents.py
  poetry.lock
  pytest
  test/workforce/test_signle_agent.py
Labels: New Feature

#803 fix: Could not install packages due to an OSError: [Errno 28] No space left on device
  .github/workflows/build_package.yml
Labels: bug

#808 fix: track_agent() got an unexpected keyword argument 'name' when without agentops
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/agents/critic_agent.py
  camel/agents/deductive_reasoner_agent.py
  camel/agents/embodied_agent.py
  camel/agents/knowledge_graph_agent.py
  camel/agents/role_assignment_agent.py
  camel/agents/search_agent.py
  camel/agents/task_agent.py
  camel/utils/__init__.py
  camel/utils/commons.py
  docs/conf.py
  docs/get_started/setup.md
  examples/bots/telegram_bot.py
  examples/observability/agentops_track_roleplaying_with_function.py
  poetry.lock
  pyproject.toml
Labels: bug

#817 feat: Retrieval module support string as input
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/retrievers/auto_retriever.py
  camel/retrievers/vector_retriever.py
  camel/toolkits/retrieval_toolkit.py
  camel/toolkits/search_toolkit.py
  docs/conf.py
  docs/get_started/setup.md
  docs/key_modules/retrievers.md
  docs/tutorials_and_cookbooks/agents_with_rag.md
  examples/bots/discord_bot.py
  examples/function_call/github_examples.py
  examples/translation/translator.py
  pyproject.toml
  test/retrievers/test_auto_retriever.py
  test/retrievers/test_vector_retriever.py
Labels: enhancement

#824 fix: Lock nltk version for unstructured io
  poetry.lock
  pyproject.toml
Labels: bug

#825 feat: Add agentops support for mistral model running
  camel/models/mistral_model.py
Labels: enhancement, New Feature

#823 feat: Update Mistral version and support tool calling
  camel/configs/mistral_config.py
  camel/embeddings/mistral_embedding.py
  camel/models/mistral_model.py
  camel/utils/token_counting.py
  examples/models/role_playing_with_mistral.py
  poetry.lock
  pyproject.toml
  test/embeddings/test_mistral_embedding.py
  test/models/test_mistral_model.py
Labels: enhancement, Model

#826 release: v0.1.6.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release

#827 feat: Change auto_retriever output format
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/configs/gemini_config.py
  camel/configs/groq_config.py
  camel/configs/mistral_config.py
  camel/loaders/unstructured_io.py
  camel/retrievers/auto_retriever.py
  camel/retrievers/bm25_retriever.py
  camel/retrievers/vector_retriever.py
  camel/toolkits/retrieval_toolkit.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
  test/loaders/test_unstructured_io.py
  test/retrievers/test_auto_retriever.py
Labels: enhancement

#842 fix: Improving naming covention of ModelPlatformType
  camel/types/enums.py
Labels: bug

#856 feat: Auto retrieval support Element as input
  camel/retrievers/auto_retriever.py
  camel/retrievers/vector_retriever.py
  test/retrievers/test_auto_retriever.py
Labels: New Feature, P0

#857 release: v0.1.6.6
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release

#787 feat: Add support for open-sourced multi-modal model
  camel/messages/base.py
  camel/models/__init__.py
  camel/models/interlm_xcomposer_model.py
  camel/models/model_factory.py
  camel/types/__init__.py
  camel/types/enums.py
  examples/models/interlm_xcomposer_model_example.py
Labels: Model

#839 feat: integrate linkedin toolkit
  camel/toolkits/__init__.py
  camel/toolkits/linkedin_toolkit.py
  camel/utils/__init__.py
  camel/utils/commons.py
  test/toolkits/test_linkedin_function.py
Labels: New Feature

#872 fix: Remove collection name generator in auto_retriever
  camel/retrievers/auto_retriever.py
Labels: bug

#880 release: v 0.1.6.7
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release

#788 feat: Rebuild record memory
  camel/agents/chat_agent.py
  camel/agents/critic_agent.py
  camel/societies/babyagi_playing.py
  camel/societies/role_playing.py
  examples/code/role_playing_multiprocess.py
Labels: enhancement
