Repository camel-ai/camel, pull requests merged in 2024-06, with the labels that each got.

#573 refactor: search function refactor and multi modal support
  camel/agents/__init__.py
  camel/agents/role_assignment_agent.py
  camel/agents/search_agent.py
  camel/functions/search_functions.py
  camel/utils/__init__.py
  camel/utils/commons.py
  poetry.lock
  pyproject.toml
Labels: Refactor, New Feature

#446 feat: Integration of VLM embedding model
  camel/embeddings/__init__.py
  camel/embeddings/vlm_embedding.py
  licenses/update_license.py
  poetry.lock
  pyproject.toml
  test/embeddings/test_vlm_embeddings.py
Labels: Embeddings, size:L, lgtm

#599 fix: small enhancement for type hint and docstring
  camel/embeddings/openai_embedding.py
  camel/embeddings/sentence_transformers_embeddings.py
  camel/loaders/unstructured_io.py
  camel/models/anthropic_model.py
  camel/models/base_model.py
  camel/models/open_source_model.py
  camel/models/openai_model.py
  camel/retrievers/auto_retriever.py
  camel/storages/graph_storages/base.py
  camel/utils/__init__.py
  camel/utils/commons.py
  poetry.lock
Labels: enhancement

#602 docs: Contribution guideline update
  CONTRIBUTING.md
Labels: documentation

#440 feat: add duckduckgo search and enhance the text extraction from the website
  camel/agents/__init__.py
  camel/agents/role_assignment_agent.py
  camel/agents/search_agent.py
  camel/functions/search_functions.py
  camel/utils/__init__.py
  camel/utils/commons.py
  poetry.lock
  pyproject.toml
  test/functions/test_search_functions.py
Labels: API, FunctionCall, size:L

#612 feat: Add example for openapi functions
  examples/function_call/openapi_function.py
Labels: Example, API

#620 docs: add code review guide
  CONTRIBUTING.md
Labels: documentation

#609 feat: Support API KEY for OPENAPI functions
  camel/functions/__init__.py
  camel/functions/open_api_function.py
  camel/functions/open_api_specs/nasa_apod/__init__.py
  camel/functions/open_api_specs/nasa_apod/openapi.yaml
  camel/functions/open_api_specs/security_config.py
  camel/types/enums.py
  poetry.lock
  pyproject.toml
  test/functions/test_open_api_function.py
Labels: enhancement, API, FunctionCall

#596 feat: Add support for litellm library
  camel/configs/__init__.py
  camel/configs/litellm_config.py
  camel/models/__init__.py
  camel/models/litellm_model.py
  camel/utils/__init__.py
  camel/utils/token_counting.py
  examples/litellm_models/litellm_model_example.py
  poetry.lock
  pyproject.toml
  test/models/test_litellm_model.py
Labels: New Feature

#644 docs: Polish camel installation part
  README.md
  docs/get_started/setup.md
Labels: documentation

#582 feat: Retrive recent pull requests for GithubToolkit
  camel/toolkits/github_toolkit.py
  examples/function_call/github_examples.py
  test/toolkits/test_github_toolkit.py
Labels: New Feature

#600 feat: add_zhipuai_model
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/zhipuai_model.py
  camel/types/enums.py
  camel/utils/commons.py
  examples/zhipuai_models/zhipuai_model.py
  test/models/test_zhipuai_model.py
Labels: Model, New Feature

#646 fix: Resolve Open Source Model Initialization in model_factory.py
  camel/models/model_factory.py
Labels: bug

#654 Fix video description naming
  camel/prompts/task_prompt_template.py
  camel/types/enums.py
  examples/vision/video_description.py
Labels: Prompt, Example

#657 release: v0.1.5.2
  README.md
  docs/conf.py
  docs/get_started/setup.md
  pyproject.toml
Labels: Release

#587 fix: anthropic token counter
  camel/utils/token_counting.py
Labels: bug

#451 Add agent example use case to generate query, positive and negative examples
  camel/configs/openai_config.py
  camel/prompts/__init__.py
  camel/prompts/generate_text_embedding_data.py
  camel/prompts/task_prompt_template.py
  camel/types/enums.py
  examples/generate_text_embedding_data/single_agent.py
  examples/generate_text_embedding_data/task_generation.py
  test/prompts/test_generate_text_embedding_data.py
Labels: Prompt, Example, size:L

#661 Modify `ChatAgent` function call args json and make slack sdk optional
  camel/agents/chat_agent.py
  camel/functions/open_api_function.py
  camel/functions/slack_functions.py
Labels: bug, help wanted

#662 docs: Ollama doc
  README.md
  docs/get_started/setup.md
Labels: documentation

#659 feat: integrate nemotron API
  .github/workflows/pytest_package.yml
  camel/agents/chat_agent.py
  camel/models/__init__.py
  camel/models/nemotron_model.py
  camel/types/enums.py
  camel/utils/commons.py
  examples/models/litellm_model_example.py
  examples/models/nemotron_model_example.py
  examples/models/openai_audio_models_example.py
  examples/models/role_playing_with_claude.py
  examples/models/role_playing_with_open_source_model.py
  examples/models/zhipuai_model_example copy.py
  examples/test/test_ai_society_example.py
Labels: Model

#665 release: v0.1.5.3
  README.md
  docs/conf.py
  docs/get_started/setup.md
  examples/test/test_role_description_example.py
  pyproject.toml
Labels: Release

#628 Update sentence transformer text embeddings
  camel/embeddings/base.py
  camel/embeddings/sentence_transformers_embeddings.py
  poetry.lock
  pyproject.toml
Labels: Embeddings

#627 Update OpenAI text embeddings
  camel/embeddings/openai_embedding.py
  camel/retrievers/auto_retriever.py
  camel/types/enums.py
  docs/key_modules/embeddings.md
  test/embeddings/test_openai_embedding.py
  test/retrievers/test_auto_retriever.py
Labels: Embeddings

#669 feat: Add claude 3.5, update interface for zhipu example
  camel/types/enums.py
  examples/models/zhipuai_model_example.py
  poetry.lock
  pyproject.toml
  test/models/test_anthropic_model.py
Labels: Model

#660 feat: Discord bot rag
  camel/bots/discord_bot.py
  examples/bots/__init__.py
  examples/bots/discord_bot.py
  examples/bots/discord_bot_example.py
  examples/bots/telegram_bot.py
  examples/bots/telegram_bot_example.py
  examples/test/bots/test_discord_bot.py
  examples/test/bots/test_telegram_bot.py
Labels: Agent

#571 fix: python version update
  .github/actions/camel_install/action.yml
  .github/workflows/build_package.yml
  .github/workflows/documentation.yml
  .github/workflows/pre_commit.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: bug

#675 fix: set pillow and unstructured to be installed by default
  camel/agents/knowledge_graph_agent.py
  camel/storages/graph_storages/graph_element.py
  poetry.lock
  pyproject.toml
Labels: bug

#688 release: v0.1.5.4 and update dependency
  README.md
  docs/conf.py
  docs/get_started/setup.md
  examples/bots/discord_bot.py
  examples/function_call/github_examples.py
  examples/function_call/openapi_function.py
  examples/vision/video_description.py
  poetry.lock
  pyproject.toml
Labels: Release

#686 Add favicon to docs
  misc/favicon.png
Labels: documentation

#687 Update docs with favicon and new left bar logo and title
  docs/conf.py
Labels: documentation

#671 feat: Add redis cache storage
  camel/storages/__init__.py
  camel/storages/key_value_storages/__init__.py
  camel/storages/key_value_storages/redis.py
  examples/storages/redis_storage.py
  poetry.lock
  pyproject.toml
  test/storages/key_value_storages/test_redis.py
Labels: New Feature, P1
