Repository camel-ai/camel, pull requests merged in 2024-01, with the labels that each got.

#393 Improve function call (#279)
  camel/agents/chat_agent.py
  camel/configs.py
  camel/functions/__init__.py
  camel/functions/math_functions.py
  camel/functions/openai_function.py
  camel/functions/search_functions.py
  camel/functions/unstructured_io_fuctions.py
  camel/functions/weather_functions.py
  camel/utils/__init__.py
  camel/utils/commons.py
  examples/function_call/role_playing_with_function.py
  poetry.lock
  pyproject.toml
  test/agents/test_chat_agent.py
  test/functions/test_openai_function.py
  test/functions/test_unstructured_io_functions.py
  test/utils/test_parse_doc.py
Labels: FunctionCall

#425 feat: Implementing Structured Output Support in AI Role-Playing Module
  camel/agents/insight_agent.py
  examples/ai_society/role_playing_with_structured_output.py
  examples/multi_agent/multi_agent_communication.py
  examples/test/test_ai_society_example.py
Labels: Agent, size:L

#424 fix duplicate sys msg & consecutive user in ass agent memory
  apps/agents/agents.py
  camel/societies/role_playing.py
  examples/ai_society/role_playing.py
  examples/ai_society/role_playing_multi_lingual.py
  examples/ai_society/role_playing_multiprocess.py
  examples/ai_society/role_playing_with_critic.py
  examples/ai_society/role_playing_with_human.py
  examples/code/role_playing.py
  examples/code/role_playing_multiprocess.py
  examples/function_call/role_playing_with_function.py
  examples/misalignment/role_playing_multiprocess.py
  examples/misalignment/role_playing_with_human.py
  examples/open_source_models/role_playing_with_open_source_model.py
  examples/role_description/role_playing_with_role_description.py
  test/agents/test_role_playing.py
Labels: Message, API, Model, size:L, lgtm

#428 Lock `pydantic` to 2
  poetry.lock
  pyproject.toml
Labels: Dependency, size:XS

#429 add fake openai api key to open source model support
  camel/models/open_source_model.py
  poetry.lock
Labels: Model, size:XS, lgtm

#434 Resolve pydantic v1 conflict
  camel/functions/openai_function.py
  camel/utils/__init__.py
  camel/utils/commons.py
  poetry.lock
  pyproject.toml
  test/functions/test_openai_function.py
  test/utils/test_commons.py
Labels: bug, FunctionCall, size:L, lgtm

#437 fix(storage): Fix vectordb storage tests
  test/storages/vector_storages/test_all_vectordbs.py
  test/storages/vector_storages/test_qdrant.py
Labels: size:XS, lgtm

#439 Fix README and some other minor fixes
  README.md
  camel/agents/chat_agent.py
  camel/functions/search_functions.py
  misc/framework.png
  misc/logo.png
  test/functions/test_search_functions.py
Labels: Readme, size:L, lgtm

#441 Add new logo
  misc/primary_logo.png
Labels: Readme, size:XS
