Repository camel-ai/camel, pull requests merged in 2025-07, with the labels that each got.

#2773 docs: add Events section to README (#2655)
  README.md
Labels: documentation

#2777 docs: Add MCP Section
  docs/mintlify/docs.json
  docs/mintlify/images/camel_toolks_as_mcp_server.png
  docs/mintlify/images/claude_example1.png
  docs/mintlify/images/claude_example2.png
  docs/mintlify/images/mcp-architecture.jpeg
  docs/mintlify/images/mcp-client-server-example.png
  docs/mintlify/images/mcp-without-vs-with.jpg
  docs/mintlify/mcp/camel_agents_as_an_mcp_clients.mdx
  docs/mintlify/mcp/camel_toolkits_as_an_mcp_server.mdx
  docs/mintlify/mcp/export_camel_agent_as_mcp_server.mdx
  docs/mintlify/mcp/mcp_hub.mdx
  docs/mintlify/mcp/overview.mdx
Labels: documentation, Review Required

#2792 feat: add note taking toolkit, polish toolkit docstring and prompt
  camel/toolkits/__init__.py
  camel/toolkits/file_write_toolkit.py
  camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
  camel/toolkits/note_taking_toolkit.py
  examples/workforce/eigent.py
  test/toolkits/test_note_taking_toolkit.py
Labels: New Feature

#2795 chore: _create_file_in_container method bug in Docker interpreter
  camel/interpreters/docker_interpreter.py
Labels: bug

#2794 feat: Add traceroot example and make traceroot as an observe decorator
  camel/agents/chat_agent.py
  camel/logger.py
  camel/models/azure_openai_model.py
  camel/models/deepseek_model.py
  camel/models/gemini_model.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  examples/debug/.traceroot-config.yaml
  examples/debug/README_traceroot.md
  examples/debug/traceroot_example.py
  pyproject.toml
  test/toolkits/test_hybrid_browser_toolkit.py
  uv.lock
Labels: Example

#2799 chore: fix litellm_functioncall
  camel/models/litellm_model.py
Labels: bug

#2771 feat: Add MessageAgentTool for agent communication #2767
  camel/toolkits/message_agent_toolkit.py
  examples/toolkits/message_agent_toolkit.py
  test/toolkits/test_message_agent_toolkit.py
Labels: New Feature

#2802 enhance: Workforce failed task handling
  camel/societies/workforce/prompts.py
  camel/societies/workforce/role_playing_worker.py
  camel/societies/workforce/single_agent_worker.py
  camel/societies/workforce/utils.py
  camel/societies/workforce/workforce.py
  camel/societies/workforce/workforce_logger.py
  camel/tasks/task.py
  examples/workforce/eigent.py
  examples/workforce/hackathon_judges.py
  test/workforce/test_workforce.py
Labels: Agents

#2803 enhance: File write toolkit pdf genertaion
  camel/toolkits/file_write_toolkit.py
  pyproject.toml
  uv.lock
Labels: Tool

#2559 Support for Streaming Responses in ChatAgent
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/agents/repo_agent.py
  camel/benchmarks/browsecomp.py
  camel/messages/base.py
  camel/models/azure_openai_model.py
  camel/models/base_model.py
  camel/models/model_manager.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  docs/conf.py
  docs/mintlify/reference/camel.agents.chat_agent.mdx
  docs/mintlify/reference/camel.models.azure_openai_model.mdx
  docs/mintlify/reference/camel.models.base_model.mdx
  docs/mintlify/reference/camel.models.openai_compatible_model.mdx
  docs/mintlify/reference/camel.models.openai_model.mdx
  examples/agents/chatagent_stream.py
  pyproject.toml
  test/agents/test_repo_agent.py
  uv.lock
Labels: Waiting for Update

#2829 feat: task_stream
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/societies/workforce/single_agent_worker.py
  camel/societies/workforce/workforce.py
  camel/tasks/task.py
  docs/conf.py
  examples/workforce/eigent.py
  pyproject.toml
  uv.lock
Labels: New Feature

#2855 fix: pre-commit mypy hook to use project dependencies
  .pre-commit-config.yaml
Labels: bug

#2763 feat:origene toolkit
  camel/toolkits/__init__.py
  camel/toolkits/origene_mcp_toolkit.py
  examples/toolkits/mcp/mcp_origene_toolkit/client.py
Labels: Review Required

#2791 feat: add surrealDB in vectorstorage
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/surreal.py
  examples/storages/surreal_vector_storage.py
  pyproject.toml
  test/storages/vector_storages/test_surreal.py
  uv.lock
Labels: Waiting for Update

#2880 [BUG] HumanToolkit Provides More Explicit Feedback When Messaging User
  camel/toolkits/human_toolkit.py
  docs/mintlify/reference/camel.toolkits.human_toolkit.mdx
  docs/reference/camel.toolkits.human_toolkit.md
  examples/workforce/eigent.py
Labels: bug

#2902 enhance:type script browser
  .gitignore
  camel/agents/chat_agent.py
  camel/toolkits/hybrid_browser_toolkit/actions.py
  camel/toolkits/hybrid_browser_toolkit/agent.py
  camel/toolkits/hybrid_browser_toolkit/browser_session.py
  camel/toolkits/hybrid_browser_toolkit/config_loader.py
  camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
  camel/toolkits/hybrid_browser_toolkit/snapshot.py
  camel/toolkits/hybrid_browser_toolkit/stealth_script.js
  camel/toolkits/hybrid_browser_toolkit/ts/package-lock.json
  camel/toolkits/hybrid_browser_toolkit/ts/package.json
  camel/toolkits/hybrid_browser_toolkit/ts/src/browser-scripts.js
  camel/toolkits/hybrid_browser_toolkit/ts/src/browser-session.ts
  camel/toolkits/hybrid_browser_toolkit/ts/src/config-loader.ts
  camel/toolkits/hybrid_browser_toolkit/ts/src/hybrid-browser-toolkit.ts
  camel/toolkits/hybrid_browser_toolkit/ts/src/index.ts
  camel/toolkits/hybrid_browser_toolkit/ts/src/types.ts
  camel/toolkits/hybrid_browser_toolkit/ts/tsconfig.json
  camel/toolkits/hybrid_browser_toolkit/ts/websocket-server.js
  camel/toolkits/hybrid_browser_toolkit/unified_analyzer.js
  camel/toolkits/hybrid_browser_toolkit/ws_wrapper.py
  examples/toolkits/hybrid_browser_toolkit_example.py
  examples/workforce/eigent.py
  hatch_build_npm.py
  pyproject.toml
  test/toolkits/test_hybrid_browser_toolkit.py
  uv.lock
Labels: Review Required

#2891 fix: surrealdb integration
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/surreal.py
  examples/storages/surreal_vector_storage.py
  pyproject.toml
  test/storages/vector_storages/test_surreal.py
  uv.lock
Labels: Waiting for Update

#2954 enhance: convert unvalided mcp schema satisfy openai requirement
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/societies/__init__.py
  camel/toolkits/mcp_toolkit.py
  docs/conf.py
  examples/toolkits/mcp/mcp_toolkit.py
  pyproject.toml
  uv.lock
Labels: enhancement

#2946 feat:add qwen coder model
  camel/types/enums.py
  docs/mintlify/key_modules/models.mdx
  examples/models/qwen_model_example.py
Labels: Review Required
