Repository camel-ai/camel, pull requests merged in 2025-05, with the labels that each got.

#1699 feat: simplify creating agent using str, add examples
  camel/agents/chat_agent.py
  camel/models/model_factory.py
  docs/key_modules/agents.md
  examples/agents/agent_step_with_reasoning.py
  examples/agents/create_chat_agent.py
  examples/agents/repo_agent.py
  test/agents/test_chat_agent.py
Labels: enhancement

#2116 enhance: SingleStepEnv add timeout
  camel/environments/single_step.py
Labels: Loong

#2316 fix: Ollama and VLLM api key & url setting
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/models/ollama_model.py
  camel/models/vllm_model.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: bug

#2309 feat: Add Klavis toolkit.
  .env
  camel/toolkits/__init__.py
  camel/toolkits/klavis_toolkit.py
  camel/utils/commons.py
  docs/key_modules/tools.md
  examples/toolkits/klavis_toolkit.py
  test/toolkits/test_klavis_toolkit.py
Labels: New Feature

#2261 feat: integrating daytona runtime
  camel/runtime/__init__.py
  camel/runtime/daytona_runtime.py
  examples/runtime/daytona_runtime.py
  pyproject.toml
  test/runtime/test_daytona_runtime.py
  uv.lock
Labels: New Feature

#2295 feat: ACI_Tool_interface
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/toolkits/__init__.py
  camel/toolkits/aci_toolkit.py
  examples/agents/single_agent.py
  examples/test/test_babyagi_example.py
  examples/toolkits/aci_toolkit.py
  examples/toolkits/semantic_scholar_toolkit.py
  pyproject.toml
  test/toolkits/test_aci_toolkit.py
  uv.lock
Labels: New Feature

#2285 feat: add termination parameter to ChatAgent step and astep
  camel/agents/chat_agent.py
  camel/responses/agent_responses.py
  camel/societies/role_playing.py
Labels: enhancement

#2128 feat: enable MCP to models without function calling (same as #1978, fix for a clear git history)
  .gitignore
  camel/agents/__init__.py
  camel/agents/mcp_agent.py
  camel/toolkits/mcp_toolkit.py
  examples/agents/mcp_agent/calculator_server.py
  examples/agents/mcp_agent/mcp_agent.py
  examples/agents/mcp_agent/mcp_servers_config.json
  pyproject.toml
  uv.lock
Labels: New Feature

#2144 feat: Agent as MCP server
  camel/utils/__init__.py
  camel/utils/response_format.py
  services/README.md
  services/agent_config.py
  services/agent_mcp_server.py
  test/services/test_agent_mcp_server.py
  test/utils/test_response_format.py
Labels: New Feature

#2218 feat: add argument for using Dict as config in MCP toolkit
  camel/toolkits/mcp_toolkit.py
  examples/toolkits/mcp/mcp_toolkit.py
Labels: New Feature

#2343 feat: Pass timeout to MCP session
  camel/toolkits/mcp_toolkit.py
Labels: enhancement

#2353 feat: Add playwright mcp toolkit
  camel/toolkits/__init__.py
  camel/toolkits/playwright_mcp_toolkit.py
  examples/toolkits/openai_agent_toolkit.py
  examples/toolkits/playwright_mcp_toolkit.py
  examples/toolkits/searxng_toolkit.py
Labels: New Feature

#2354 feat: Support Mistral medium
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/types/enums.py
  docs/conf.py
  docs/key_modules/loaders.md
  examples/models/mistral_model_example.py
  pyproject.toml
  test/models/test_mistral_model.py
  uv.lock
Labels: Model, New Feature

#2333 feat: mcp server launch with better interface
  camel/toolkits/base.py
  docs/key_modules/tools.md
  examples/mcp_arxiv_toolkit/arxiv_toolkit_server.py
Labels: enhancement

#2373 docs: clarify use of .env and automatic loading in pytest
  CONTRIBUTING.md
  test/conftest.py
Labels: New Feature

#2222 feat: add MCP search agent
  camel/agents/chat_agent.py
  camel/agents/mcp_agent.py
  camel/toolkits/mcp_toolkit.py
  camel/types/__init__.py
  camel/types/mcp_registries.py
  examples/agents/mcp_agent/mcp_agent_using_registry.py
  examples/agents/mcp_agent/mcp_agent_without_function_calling.py
Labels: New Feature

#2310 doc: Camel MCP cookbook
  docs/cookbooks/advanced_features/agents_with_MCP.ipynb
  docs/cookbooks/advanced_features/index.rst
Labels: cookbook

#2407 chore: fixed typos in and edited agents_with_MCP cookbook
  docs/cookbooks/advanced_features/agents_with_MCP.ipynb
Labels: cookbook

#2293 feat: Integrating BrowseComp Benchmark
  camel/agents/chat_agent.py
  camel/agents/critic_agent.py
  camel/benchmarks/__init__.py
  camel/benchmarks/browsecomp.py
  camel/human.py
  camel/societies/role_playing.py
  camel/societies/workforce/role_playing_worker.py
  camel/societies/workforce/workforce.py
  examples/benchmarks/browsecomp_chat_agent.py
  examples/benchmarks/browsecomp_roleplaying.py
  examples/benchmarks/browsecomp_workforce.py
Labels: New Feature

#2416 fix: Multi-round step running token count in ChatAgent
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/chat_agent.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: bug

#2425 fix: minor bug in http runtime example
  examples/runtime/remote_http_runtime.py
Labels: bug

#2424 feat: streamable HTTP
  camel/toolkits/mcp_toolkit.py
  examples/mcp_arxiv_toolkit/mcp_servers_config.json
Labels: New Feature

#2397 feat: update Gemini model types, fix Gemini-2.0-Flash matching issue
  camel/types/enums.py
  docs/key_modules/models.md
  examples/models/gemini_model_example.py
Labels: enhancement

#2405 test: Integration test - minimal dependency check
  .github/workflows/test_minimal_dependency.yml
  .pre-commit-config.yaml
  camel/configs/cohere_config.py
  camel/configs/mistral_config.py
  camel/configs/reka_config.py
  camel/configs/samba_config.py
  camel/embeddings/jina_embedding.py
  camel/embeddings/sentence_transformers_embeddings.py
  camel/embeddings/vlm_embedding.py
  camel/memories/records.py
  camel/messages/base.py
  camel/models/model_factory.py
  camel/retrievers/bm25_retriever.py
  camel/retrievers/hybrid_retrival.py
  camel/storages/vectordb_storages/oceanbase.py
  camel/toolkits/async_browser_toolkit.py
  camel/toolkits/browser_toolkit.py
  camel/toolkits/dalle_toolkit.py
  camel/toolkits/excel_toolkit.py
  camel/toolkits/image_analysis_toolkit.py
  camel/toolkits/twitter_toolkit.py
  camel/toolkits/video_analysis_toolkit.py
  camel/toolkits/video_download_toolkit.py
  pyproject.toml
  test/integration_test/test_minimal_dependency.py
  uv.lock
Labels: Test

#2059 fix: roi rectangle adapt to retina display
  camel/toolkits/page_script.js
Labels: enhancement

#2289 fix: rename monte_carlo_tree_search to evaluate_partial_solution and clarify solve docstring
  camel/datagen/cot_datagen.py
Labels: enhancement

#2258 feat: jina reranker refactor + api support
  camel/toolkits/jina_reranker_toolkit.py
  examples/toolkits/jina_reranker_toolkit.py
  test/toolkits/test_jina_reranker_toolkit.py
Labels: New Feature

#2438 chore: relax numpy versions
  pyproject.toml
  uv.lock
Labels: Review Required

#2434 feat: extra headers for azure openai
  camel/configs/openai_config.py
  camel/models/azure_openai_model.py
Labels: New Feature, Review Required

#2447 refactor: Wolfram Alpha and Github Toolkit
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/toolkits/github_toolkit.py
  camel/toolkits/wolfram_alpha_toolkit.py
  docs/conf.py
  docs/key_modules/loaders.md
  examples/toolkits/github_toolkit.py
  examples/toolkits/wolfram_alpha_toolkit.py
  pyproject.toml
  test/toolkits/test_github_toolkit.py
  test/toolkits/test_wolframalpha_toolkit.py
  uv.lock
Labels: enhancement

#2409 feat: Bohrium integrate
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/toolkits/__init__.py
  camel/toolkits/bohrium_toolkit.py
  examples/toolkits/bohrium_toolkit_example.py
  examples/toolkits/bohrium_toolkit_example.yaml
  pyproject.toml
  test/toolkits/test_bohrium_toolkit.py
  uv.lock
Labels: New Feature, Review Required

#2437 doc: Add doc for runtime module
  docs/index.rst
  docs/key_modules/runtimes.md
Labels: documentation, Review Required, Waiting for Update

#2453 fix: example of workforce bug
  examples/workforce/role_playing_with_agents.py
Labels: bug

#2376 feat: update evol_instruct
  camel/datagen/evol_instruct/scorer.py
  camel/datagen/evol_instruct/templates.py
  examples/datagen/evol_instruct/evol_instruct.py
  examples/datagen/evol_instruct/results.json
  examples/datagen/evol_instruct/results_iter.json
  examples/datagen/evol_instruct/results_iter_harder.json
Labels: Review Required

#2034 `feat: Add new vector storage db FAISS`
  camel/storages/__init__.py
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/faiss.py
  docs/camel.storages.vectordb_storages.rst
  pyproject.toml
  test/storages/vector_storages/test_faiss.py
  uv.lock
Labels: New Feature

#2063 docs : Cookbook on using MCP with CAMEL on SQL
  docs/cookbooks/loong/index.rst
  docs/cookbooks/mcp/agents_with_sql_mcp.ipynb
  docs/cookbooks/mcp/index.rst
  docs/index.rst
Labels: cookbook

#2201 `ChatAgent` is able to accept a `ModelManager` as model's input.
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/models/model_manager.py
  camel/toolkits/bohrium_toolkit.py
  docs/conf.py
  docs/key_modules/loaders.md
  docs/mintlify/convert_notebook2mdx.py
  docs/mintlify/key_modules/loaders.mdx
  docs/mintlify/reference/camel.agents.chat_agent.mdx
  docs/mintlify/reference/camel.toolkits.bohrium_toolkit.mdx
  examples/agent/agents_share_modelmanager.py
  pyproject.toml
  test/toolkits/test_bohrium_toolkit.py
  uv.lock
Labels: Refactor

#2479 feat: Add new Mistral Document AI for advanced OCR processing
  camel/loaders/__init__.py
  camel/loaders/mistral_reader.py
  docs/key_modules/loaders.md
  examples/loaders/mistral_example.py
  test/loaders/test_mistral_reader.py
Labels: Model, New Feature

#2506 enhance: Workforce Docstring
  camel/societies/workforce/workforce.py
  docs/mintlify/docs.json
  docs/mintlify/reference/camel.loaders.mistral_reader.mdx
  docs/mintlify/reference/camel.societies.workforce.workforce.mdx
Labels: documentation, enhancement, Society

#2475 feat: pptx toolkit
  camel/toolkits/__init__.py
  camel/toolkits/file_write_toolkit.py
  camel/toolkits/pptx_toolkit.py
  docs/key_modules/tools.md
  docs/mintlify/docs.json
  docs/mintlify/reference/camel.datasets.static_dataset.mdx
  docs/mintlify/reference/camel.toolkits.file_write_toolkit.mdx
  docs/mintlify/reference/camel.toolkits.pptx_toolkit.mdx
  examples/toolkits/pptx_toolkit.py
  examples/toolkits/slides_templates/blank.pptx
  examples/toolkits/slides_templates/ion_boardroom.pptx
  examples/toolkits/slides_templates/minimalist_sales_pitch.pptx
  examples/toolkits/slides_templates/modern.pptx
  examples/toolkits/slides_templates/urban_monochrome.pptx
  pyproject.toml
  test/toolkits/test_pptx_toolkit.py
  uv.lock
Labels: New Feature
