Repository camel-ai/camel, pull requests merged in 2025-04, with the labels that each got.

#1999 feat: camel toolkits as mcp server
  camel/toolkits/__init__.py
  camel/toolkits/arxiv_toolkit.py
  camel/toolkits/ask_news_toolkit.py
  camel/toolkits/audio_analysis_toolkit.py
  camel/toolkits/base.py
  camel/toolkits/code_execution.py
  camel/toolkits/dappier_toolkit.py
  camel/toolkits/data_commons_toolkit.py
  camel/toolkits/excel_toolkit.py
  camel/toolkits/file_write_toolkit.py
  camel/toolkits/github_toolkit.py
  camel/toolkits/google_scholar_toolkit.py
  camel/toolkits/image_analysis_toolkit.py
  camel/toolkits/linkedin_toolkit.py
  camel/toolkits/math_toolkit.py
  camel/toolkits/meshy_toolkit.py
  camel/toolkits/networkx_toolkit.py
  camel/toolkits/notion_toolkit.py
  camel/toolkits/openbb_toolkit.py
  camel/toolkits/pubmed_toolkit.py
  camel/toolkits/reddit_toolkit.py
  camel/toolkits/retrieval_toolkit.py
  camel/toolkits/search_toolkit.py
  camel/toolkits/semantic_scholar_toolkit.py
  camel/toolkits/slack_toolkit.py
  camel/toolkits/stripe_toolkit.py
  camel/toolkits/sympy_toolkit.py
  camel/toolkits/terminal_toolkit.py
  camel/toolkits/twitter_toolkit.py
  camel/toolkits/video_analysis_toolkit.py
  camel/toolkits/video_download_toolkit.py
  camel/toolkits/weather_toolkit.py
  camel/toolkits/whatsapp_toolkit.py
  camel/toolkits/zapier_toolkit.py
  camel/utils/__init__.py
  camel/utils/mcp.py
  docs/key_modules/tools.md
  examples/mcp_arxiv_toolkit/arxiv_toolkit_server.py
  examples/mcp_arxiv_toolkit/client.py
  examples/mcp_arxiv_toolkit/mcp_servers_config.json
  test/utils/test_mcp_server.py
Labels: New Feature

#2091 fix: improve error handling and resource cleanup in MCP toolkit
  .env
  camel/toolkits/mcp_toolkit.py
  test/toolkits/test_video_download_function.py
Labels: enhancement

#2087 feat: add send_message_to_user method to human_toolkit for direct user messaging
  camel/toolkits/human_toolkit.py
  examples/toolkits/human_toolkit.py
Labels: enhancement, New Feature

#2068 fix: Agent can't retrieve the system_msg
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/memories/blocks/chat_history_block.py
  camel/types/enums.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  test/agents/test_chat_agent.py
  uv.lock
Labels: bug

#2111 chore: add time out to few shot generator
  camel/datasets/few_shot_generator.py
Labels: enhancement

#2118 fix: Vllm tool call schema remove additionalProperties
  camel/models/vllm_model.py
Labels: bug

#2119 fix: enhance timestamp for agent memory update
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/chat_agent.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: enhancement

#2133 update: add float type comparison
  camel/verifiers/python_verifier.py
  test/verifiers/test_python_verifier.py
Labels: enhancement, Loong

#2123 feat: llama4 support in openrouter
  camel/types/enums.py
  examples/models/openrouter_llama3.1_example .py
  examples/models/openrouter_llama4_example.py
Labels: New Feature

#2134 fix: remove strict param in vllm model
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/models/azure_openai_model.py
  camel/models/cohere_model.py
  camel/models/deepseek_model.py
  camel/models/gemini_model.py
  camel/models/ollama_model.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  camel/models/vllm_model.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: bug, enhancement

#2115 feat: add exa search
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
  pyproject.toml
  uv.lock
Labels: New Feature

#2141 chore: add warning message to workforce default model setting
  camel/societies/workforce/workforce.py
Labels: enhancement

#2051 feat: adding google calendar toolkit
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/toolkits/__init__.py
  camel/toolkits/google_calendar_toolkit.py
  docs/key_modules/tools.md
  examples/toolkits/google_calendar_toolkit.py
  pyproject.toml
  test/toolkits/test_google_calendar_toolkit.py
  uv.lock
Labels: New Feature

#2143 feat: add together embedding
  camel/embeddings/__init__.py
  camel/embeddings/together_embedding.py
  camel/toolkits/google_calendar_toolkit.py
  examples/embeddings/together_embedding_example.py
Labels: New Feature

#2148 fix: parallel tool call sequence bug, upadte doc and readme
  README.md
  camel/embeddings/azure_embedding.py
  camel/models/base_model.py
  camel/toolkits/google_calendar_toolkit.py
  docs/key_modules/embeddings.md
  misc/wechat.jpg
  test/models/test_base_model.py
Labels: bug, enhancement

#2000 feat: Add unitests for BrowserToolkit
  camel/toolkits/browser_toolkit.py
  examples/toolkits/browser_toolkit.py
  test/toolkits/test_browser_toolkit.py
Labels: enhancement

#2095 chore: Fixing various typos in diverse notebooks
  docs/cookbooks/applications/finance_discord_bot.ipynb
  docs/cookbooks/basic_concepts/agents_message.ipynb
  docs/cookbooks/data_generation/sft_data_generation_and_unsloth_finetuning_Qwen2_5_7B.ipynb
  docs/cookbooks/data_generation/sft_data_generation_and_unsloth_finetuning_mistral_7b_instruct.ipynb
  docs/cookbooks/data_generation/sft_data_generation_and_unsloth_finetuning_tinyllama.ipynb
  docs/cookbooks/multi_agent_society/workforce_judge_committee.ipynb
Labels: documentation

#2167 fix: Enable extractor to handle single boxed backslashes
  camel/extractors/python_strategies.py
  test/extractors/test_python_strategies.py
Labels: enhancement, Loong

#2168 refactor: Together AI using beta client for structured output & support llama4
  camel/models/togetherai_model.py
  camel/toolkits/browser_toolkit.py
  camel/types/enums.py
  examples/models/togetherai_model_example.py
Labels: enhancement

#2171 chore: adding missing timeout in toolkits
  camel/toolkits/audio_analysis_toolkit.py
  camel/toolkits/dalle_toolkit.py
  camel/toolkits/excel_toolkit.py
  camel/toolkits/image_analysis_toolkit.py
  camel/toolkits/networkx_toolkit.py
  camel/toolkits/openai_agent_toolkit.py
  camel/toolkits/searxng_toolkit.py
  camel/toolkits/slack_toolkit.py
  camel/toolkits/video_analysis_toolkit.py
  camel/toolkits/weather_toolkit.py
  camel/toolkits/zapier_toolkit.py
Labels: enhancement

#2186 chore: add timeout setting for all model backend
  camel/models/cohere_model.py
  camel/models/litellm_model.py
  camel/models/mistral_model.py
  camel/models/reka_model.py
  camel/models/volcano_model.py
Labels: enhancement

#2188 feat: Support OpenAI gpt 4.1
  camel/models/litellm_model.py
  camel/types/enums.py
  examples/models/openai_gpt_4.1_example.py
Labels: New Feature

#2029 feat: Add pyautogui toolkit
  camel/toolkits/__init__.py
  camel/toolkits/pyautogui_toolkit.py
  examples/toolkits/pyautogui_toolkit.py
  pyproject.toml
  test/toolkits/test_pyautogui_toolkit.py
  uv.lock
Labels: New Feature

#1194 feat: update aws_bedrock
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/bedrock_config.py
  camel/models/__init__.py
  camel/models/aws_bedrock_model.py
  camel/models/model_factory.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/aws_bedrock_model_example.py
  test/models/test_aws_bedrock_model.py
Labels: Model

#2228 enhance: video toolkit refator PR #1852
  camel/toolkits/video_analysis_toolkit.py
  uv.lock
Labels: Refactor

#2230 fix: Qwen config extra_body type
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/configs/qwen_config.py
  docs/conf.py
  docs/cookbooks/loong/batched_single_step_env.ipynb
  docs/cookbooks/loong/multi_step_rl.ipynb
  docs/cookbooks/loong/single_step_env.ipynb
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: bug

#2247 chore: Support O4-mini, O3, fix FewShotGenerator bug, update browser toolkit
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/datasets/few_shot_generator.py
  camel/datasets/models.py
  camel/models/openai_model.py
  camel/toolkits/browser_toolkit.py
  camel/types/enums.py
  camel/utils/token_counting.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  test/datasets/test_base_dataset.py
  test/models/test_openai_model.py
  uv.lock
Labels: enhancement

#2250 enhance: Integrate Oceanbase database #2244
  camel/storages/vectordb_storages/oceanbase.py
  pyproject.toml
  test/storages/vector_storages/test_oceanbase.py
  uv.lock
Labels: enhancement

#2244 feat: Integrate Oceanbase database
  camel/storages/__init__.py
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/oceanbase.py
  examples/storages/oceanbase_vector_storage.py
  pyproject.toml
  test/storages/vector_storages/test_oceanbase.py
  uv.lock
Labels: New Feature

#2170 feat: Jina reranker toolkit
  camel/toolkits/__init__.py
  camel/toolkits/jina_reranker_toolkit.py
  docs/key_modules/tools.md
  examples/toolkits/jina_reranker_toolkit.py
  test/toolkits/test_jina_reranker_toolkit.py
Labels: Tool

#2127 feat(search_toolkit): Add Alibaba Tongxiao Search API Support
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
Labels: New Feature

#2206 feat: add scrapegraph-sdk integration
  camel/loaders/scrapegraph_reader.py
  examples/loaders/scrapegraph_example.py
  pyproject.toml
  test/loaders/test_scrapegraph_reader.py
Labels: New Feature

#2273 fix: ChatAgent astep bug
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/chat_agent.py
  camel/toolkits/dalle_toolkit.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  test/agents/test_chat_agent.py
  test/toolkits/test_dalle_functions.py
  uv.lock
Labels: bug

#2234 fix: unstable `test_tool_calling_math_async`
  camel/utils/mcp.py
  test/agents/test_chat_agent.py
Labels: Test

#2276 fix: milvus query
  camel/storages/vectordb_storages/milvus.py
  test/storages/vector_storages/test_milvus.py
Labels: bug

#2268 feat:add Netmind platform
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/netmind_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/netmind_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/netmind_model_example.py
  test/models/test_netmind_model.py
Labels: New Feature

#2187 docs: Discord customer service agent using cohere model cookbook
  docs/cookbooks/applications/customer_service_Discord_bot_using_Cohere_model_with_agentic_RAG.ipynb
Labels: cookbook

#2284 feat: Add a new llm provider - novita
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/novita_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/novita_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/novita_model_example.py
  test/models/test_novita_model.py
Labels: New Feature

#2294 feat: Support Qwen 3 in modelscope
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/configs/modelscope_config.py
  camel/models/modelscope_model.py
  camel/types/enums.py
  docs/conf.py
  docs/key_modules/loaders.md
  examples/models/modelscope_model_example.py
  pyproject.toml
  uv.lock
Labels: New Feature

#2138 feat: Physics verifier
  camel/verifiers/__init__.py
  camel/verifiers/physics_verifier.py
  camel/verifiers/python_verifier.py
  examples/verifier/physics_verifier_example.py
  pyproject.toml
Labels: New Feature

#2232 [Browser Toolkit] Better filename from url and browser toolkit cleaning
  camel/toolkits/browser_toolkit.py
  camel/utils/__init__.py
  camel/utils/filename.py
  camel/verifiers/physics_verifier.py
  test/utils/test_filename.py
Labels: Utils, Tool

#2297 feat: Integrate watson x
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/watsonx_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/watsonx_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/watsonx_model_example.py
  pyproject.toml
  test/models/test_watsonx_model.py
  uv.lock
Labels: New Feature
