Repository camel-ai/camel, pull requests merged in 2025-09, with the labels that each got.

#3087 [Feat] Integrate Wechat
  camel/toolkits/__init__.py
  camel/toolkits/wechat_official_toolkit.py
  examples/toolkits/wechat_official_toolkit.py
  test/toolkits/test_wechat_official_toolkit.py
Labels: New Feature

#3023 [Feat] Add Google vertex ai veo toolkit for video generation
  camel/storages/object_storages/google_cloud.py
  camel/toolkits/__init__.py
  camel/toolkits/vertex_ai_veo_toolkit.py
  examples/toolkits/vertex_ai_veo_toolkit.py
  pyproject.toml
  test/toolkits/test_vertex_ai_veo_toolkit.py
  uv.lock
Labels: New Feature, Waiting for Update

#2934 [feat] Markdown Agent Context Handling
  camel/agents/chat_agent.py
  camel/memories/__init__.py
  camel/memories/agent_memories.py
  camel/memories/blocks/chat_history_block.py
  camel/toolkits/__init__.py
  camel/toolkits/context_summarizer_toolkit.py
  camel/toolkits/note_taking_toolkit.py
  camel/utils/context_utils.py
  examples/toolkits/context_summarizer_toolkit.py
  test/toolkits/test_context_summarizer_toolkit.py
Labels: enhancement, Agents, Memory

#3034 feat: Improve agent pool efficiency and add performance metrics
  camel/societies/workforce/single_agent_worker.py
  pyproject.toml
Labels: Waiting for Update

#3063 feat: Dynamic File Editing
  camel/toolkits/__init__.py
  camel/toolkits/context_summarizer_toolkit.py
  camel/toolkits/file_toolkit.py
  camel/toolkits/markitdown_toolkit.py
  examples/toolkits/file_toolkit.py
  test/toolkits/test_file_toolkit.py
Labels: New Feature, Waiting for Update

#2948 feat: add ArtifactTool to make the experience similar to claude #2546
  camel/toolkits/__init__.py
  camel/toolkits/artifact_toolkit.py
  examples/toolkits/artifact_toolkit.py
  pyproject.toml
  test/toolkits/test_artifact_toolkit.py
Labels: Waiting for Update

#3147 chore: add .env.example, ignore real env files, update README setup
  .env.example
  .gitignore
  README.md
Labels: enhancement

#3127 Run containers as non-root with host UID/GID mapping
  .container/Dockerfile
  .container/docker-compose.yaml
  .container/minimal_build/Dockerfile
  camel/interpreters/docker/Dockerfile
Labels: Review Required

#2924 chore(deps): bump docstring-parser from 0.15 to 0.17.0
  pyproject.toml
  uv.lock
Labels: Review Required

#3015 feat: refactor terminal_toolkit
  camel/toolkits/terminal_toolkit.py
  camel/toolkits/terminal_toolkit/__init__.py
  camel/toolkits/terminal_toolkit/terminal_toolkit.py
  camel/toolkits/terminal_toolkit/utils.py
  test/toolkits/test_terminal_toolkit.py
Labels: Review Required

#3170 chore: fix_schema-is-broken-in-workforce
  camel/agents/chat_agent.py
  camel/societies/workforce/workforce.py
Labels: bug

#3178 docs: add Japanese README
  README.ja.md
  README.md
  README.zh.md
Labels: documentation
