Repository camel-ai/camel, pull requests merged in 2025-06, with the labels that each got.

#2496 refactor: improve mcp toolkit module
  camel/agents/mcp_agent.py
  camel/toolkits/mcp_toolkit.py
  camel/utils/mcp_client.py
  docs/mintlify/docs.json
  docs/mintlify/reference/camel.toolkits.mcp_toolkit.mdx
  docs/mintlify/reference/camel.utils.mcp_client.mdx
  examples/toolkits/mcp/mcp_arxiv_toolkit/client.py
  examples/toolkits/mcp/mcp_arxiv_toolkit/client_sync.py
  examples/toolkits/mcp/mcp_arxiv_toolkit/mcp_servers_config.json
  examples/toolkits/mcp/mcp_toolkit.py
  test/toolkits/test_mcp_toolkit.py
  test/utils/test_mcp_client.py
  test/utils/test_mcp_server.py
Labels: Refactor

#2544 fix: doc ci enhance
  .github/workflows/documentation.yml
Labels: documentation

#2554 chore: minor changes #2490
  examples/usecases/aci_mcp/README.md
  examples/usecases/aci_mcp/aci_toolkit_camel.py
  examples/usecases/aci_mcp/camel_mcp_aci.py
  examples/usecases/aci_mcp/create_config.py
  examples/usecases/aci_mcp/env.example
Labels: Waiting for Update

#2550 feat: add to_mcp and example in workforce
  camel/societies/workforce/role_playing_worker.py
  camel/societies/workforce/workforce.py
  docs/mintlify/reference/camel.societies.workforce.workforce.mdx
  examples/workforce/simple_workforce_mcp.py
Labels: Review Required

#2508 feat:Add Crynux as a LLM provider
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/crynux_config.py
  camel/models/__init__.py
  camel/models/crynux_model.py
  camel/models/model_factory.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/crynux_model_example.py
  test/models/test_crynux_model.py
Labels: New Feature, Waiting for Update

#2520 feat: Workforce add attempt information as Task additional info
  camel/societies/workforce/single_agent_worker.py
  camel/tasks/task.py
  docs/mintlify/reference/camel.tasks.task.mdx
Labels: Agents, New Feature

#2523 usecase: Youtube ocr usecase
  examples/usecases/youtube_ocr/README.md
  examples/usecases/youtube_ocr/app.py
  examples/usecases/youtube_ocr/requirements.txt
Labels: Waiting for Update

#2594 feat: add Magistral Medium (magistral-medium-2506) model support
  camel/types/enums.py
  docs/key_modules/models.md
  examples/models/mistral_model_example.py
  test/models/test_mistral_model.py
Labels: Model

#2495 feat: Dynamic dependency loading
  camel/interpreters/base.py
  camel/interpreters/docker/Dockerfile
  camel/interpreters/docker_interpreter.py
  camel/interpreters/e2b_interpreter.py
  camel/interpreters/internal_python_interpreter.py
  camel/interpreters/ipython_interpreter.py
  camel/interpreters/subprocess_interpreter.py
  camel/toolkits/code_execution.py
  docs/mintlify/reference/camel.interpreters.base.mdx
  docs/mintlify/reference/camel.interpreters.docker_interpreter.mdx
  docs/mintlify/reference/camel.interpreters.e2b_interpreter.mdx
  docs/mintlify/reference/camel.interpreters.internal_python_interpreter.mdx
  docs/mintlify/reference/camel.interpreters.ipython_interpreter.mdx
  docs/mintlify/reference/camel.interpreters.subprocess_interpreter.mdx
  docs/mintlify/reference/camel.toolkits.code_execution.mdx
  examples/toolkits/dynamic_dependency.py
  test/toolkits/test_code_execution.py
Labels: New Feature, Review Required

#2291 feat: Support persistent context and stealth mode
  camel/toolkits/async_browser_toolkit.py
  camel/toolkits/browser_toolkit.py
  docs/mintlify/reference/camel.toolkits.async_browser_toolkit.mdx
  docs/mintlify/reference/camel.toolkits.browser_toolkit.mdx
  examples/toolkits/browser_toolkit_with_user_data_dir.py
  test/toolkits/test_async_browser_toolkit.py
  test/toolkits/test_browser_toolkit.py
Labels: Review Required

#2625 feat: Set tool schema follow strict mode
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/build_package.yml
  camel/__init__.py
  camel/agents/mcp_agent.py
  camel/toolkits/function_tool.py
  camel/toolkits/mcp_toolkit.py
  camel/utils/mcp_client.py
  docs/conf.py
  examples/toolkits/playwright_mcp_toolkit.py
  pyproject.toml
  test/toolkits/test_generate_openai_tool_schema.py
  uv.lock
Labels: enhancement

#2551 [Feature Request] Enhancing robustness of Async operations in core modules #2468
  camel/environments/multi_step.py
  camel/environments/single_step.py
  camel/environments/tic_tac_toe.py
  camel/societies/role_playing.py
  camel/societies/workforce/role_playing_worker.py
  camel/societies/workforce/task_channel.py
  camel/societies/workforce/worker.py
  camel/societies/workforce/workforce.py
  camel/utils/__init__.py
  camel/utils/commons.py
  camel/utils/constants.py
  camel/verifiers/base.py
  camel/verifiers/python_verifier.py
  test/environments/test_multi_step_env.py
  test/environments/test_single_step_env.py
  test/environments/test_tictactoe_env.py
  test/verifiers/test_base_verifier.py
  test/verifiers/test_python_verifier.py
  test/workforce/test_role_play.py
  test/workforce/test_worker.py
  test/workforce/test_workforce.py
Labels: Waiting for Update

#2620 feat:integrate qianfan platform
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/qianfan_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/qianfan_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/qianfan_model_example.py
  test/models/test_qianfan_model.py
Labels: Review Required

#2305 feat(environments): add RLCards environments for Project loong board game following the multi-step Env for RL purposes
  camel/environments/__init__.py
  camel/environments/rlcards_env.py
  examples/environments/rlcards_example.py
  pyproject.toml
  uv.lock
Labels: Review Required

#2683 feat: Workforce support parallelization to further improve efficiency
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/environments/rlcards_env.py
  camel/societies/workforce/prompts.py
  camel/societies/workforce/single_agent_worker.py
  camel/societies/workforce/task_channel.py
  camel/societies/workforce/worker.py
  camel/societies/workforce/workforce.py
  docs/conf.py
  examples/workforce/eigent.py
  pyproject.toml
  uv.lock
Labels: Agents

#2691 add extra_body in vllm config
  camel/configs/vllm_config.py
Labels: enhancement

#2684 Docs: Improvising the Key Module Section
  camel/configs/vllm_config.py
  docs/cookbooks/data_processing/summarisation_agent_with_mistral_ocr.ipynb
  docs/mintlify/cookbooks/data_processing/summarisation_agent_with_mistral_ocr.mdx
  docs/mintlify/key_modules/agents.mdx
  docs/mintlify/key_modules/datagen.mdx
  docs/mintlify/key_modules/embeddings.mdx
  docs/mintlify/key_modules/interpreters.mdx
  docs/mintlify/key_modules/loaders.mdx
  docs/mintlify/key_modules/memory.mdx
  docs/mintlify/key_modules/messages.mdx
  docs/mintlify/key_modules/models.mdx
  docs/mintlify/key_modules/prompts.mdx
  docs/mintlify/key_modules/retrievers.mdx
  docs/mintlify/key_modules/runtimes.mdx
  docs/mintlify/key_modules/society.mdx
  docs/mintlify/key_modules/storages.mdx
  docs/mintlify/key_modules/tasks.mdx
  docs/mintlify/key_modules/tools.mdx
  docs/mintlify/key_modules/workforce.mdx
Labels: Review Required

#2689 feat: Single very long message processing
  camel/agents/chat_agent.py
  camel/memories/context_creators/score_based.py
  camel/toolkits/non_visual_browser_toolkit/nv_browser_session.py
Labels: Memory

#2694 Docs: Remove Bugs and improve indentation
  docs/mintlify/cookbooks/data_processing/summarisation_agent_with_mistral_ocr.mdx
  docs/mintlify/docs.json
  docs/mintlify/key_modules/memory.mdx
  docs/mintlify/key_modules/runtimes.mdx
  docs/mintlify/key_modules/societies.mdx
  docs/mintlify/key_modules/tools.mdx
Labels: Review Required

#2671 enhance: added more logging and exception handling to workforce
  camel/societies/workforce/single_agent_worker.py
Labels: Agents

#2717 feat: set craw4ai and markitdown as toolkit
  camel/toolkits/__init__.py
  camel/toolkits/craw4ai_toolkit.py
  camel/toolkits/markitdown_toolkit.py
  examples/workforce/eigent.py
Labels: Tool

#2716 feat: add google drive
  camel/memories/context_creators/score_based.py
  camel/toolkits/__init__.py
  camel/toolkits/google_drive_mcp_toolkit.py
  examples/toolkits/goole_drive_mcp_toolkit.py
  examples/workforce/eigent.py
Labels: Waiting for Update

#2697 feat: task support adding multi modal information
  camel/messages/base.py
  camel/tasks/task.py
  examples/tasks/multi_modal_task_generation.py
  examples/tasks/task_image.png
  examples/tasks/task_video.mov
  examples/workforce/eigent.py
  test/models/test_model_manager.py
  test/tasks/test_task.py
Labels: Review Required

#2656 fix: resolve openai strict conflict with dynamic router function
  camel/agents/chat_agent.py
  camel/toolkits/mcp_toolkit.py
  examples/agents/mcp_agent/mcp_agent_using_registry.py
Labels: Review Required

#2699 Add chroma vector database
  camel/storages/__init__.py
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/chroma.py
  docs/get_started/installation.md
  docs/key_modules/storages.md
  examples/storages/chroma_vector_storage.py
  pyproject.toml
  uv.lock
Labels: Review Required

#2723 [enhance] Improve the Robustness of the Task Assignment in Workforce
  camel/societies/workforce/workforce.py
Labels: enhancement, Society

#2687 feat: Enhance_excel_toolkit
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/toolkits/excel_toolkit.py
  docs/conf.py
  examples/toolkits/excel_toolkit.py
  examples/workforce/eigent.py
  pyproject.toml
  test/toolkits/test_excel_toolkit.py
  uv.lock
Labels: Tool, Waiting for Update

#2727 feat: add PgVectorStorage implementation for PostgreSQL with pgvector support
  camel/storages/__init__.py
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/pgvector.py
  docs/get_started/installation.md
  docs/key_modules/storages.md
  examples/storages/pgvector_storage.py
  pyproject.toml
  test/storages/vector_storages/test_pgvector.py
  uv.lock
Labels: RAG

#2733 feat: Add Mistral Small 3.2
  camel/types/enums.py
  docs/mintlify/key_modules/models.mdx
  examples/models/mistral_model_example.py
  test/models/test_mistral_model.py
Labels: Model

#2751 feat: terminal_human_in_the_loop
  camel/toolkits/terminal_toolkit.py
  examples/toolkits/terminal_toolkit.py
Labels: Tool

#2648 feat: Add Message Summarizer Feature
  camel/agents/chat_agent.py
  camel/utils/message_summarizer.py
  test/utils/test_message_summarizer.py
Labels: Review Required

#2748 feat:enhance pdf in filewriter
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/toolkits/file_write_toolkit.py
  docs/conf.py
  pyproject.toml
  uv.lock
Labels: Waiting for Update

#2375 feat: ChatAgent be called via traditional service like OpenAPI
  camel/services/agent_openapi_server.py
  examples/services/agent_openapi_server.py
  test/services/test_agent_openapi_server.py
Labels: Review Required
