Repository camel-ai/camel, pull requests merged in 2025-01, with the labels that each got.

#1300 feat: Integrate OpenBB Into Camel
  .env
  camel/toolkits/__init__.py
  camel/toolkits/notion_toolkit.py
  camel/toolkits/openbb_toolkit.py
  examples/toolkits/openbb_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_openbb_functions.py
Labels: New Feature

#1379 Fix: circular import of `FunctionTool` and `ChatAgent`
  camel/toolkits/function_tool.py
Labels: bug

#1383 feat: nebula graph add time label
  camel/storages/graph_storages/nebula_graph.py
  test/storages/graph_storages/test_nebula_graph.py
Labels: enhancement

#1317 chore: sglang doc, logger setting, version release
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  camel/__init__.py
  camel/logger.py
  docs/cookbooks/cot_data_gen_sft_qwen_unsolth_upload_huggingface.ipynb
  docs/cookbooks/cot_data_gen_upload_to_huggingface.py.ipynb
  docs/cookbooks/customer_service_Discord_bot_using_local_model_with_agentic_RAG.ipynb
  docs/get_started/installation.md
  docs/key_modules/models.md
  examples/models/sglang_model_example.py
  poetry.lock
  pyproject.toml
Labels: documentation

#1393 feat: Add Dappier toolkit
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/toolkits/__init__.py
  camel/toolkits/dappier_toolkit.py
  examples/toolkits/dappier_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_dappier_function.py
Labels: New Feature

#1390 fix: incorrect role assigning in rewardmodelfilter
  .github/ISSUE_TEMPLATE/bug_report.yml
  .pre-commit-config.yaml
  README.md
  camel/__init__.py
  camel/datagen/self_instruct/filter/filter_function.py
  camel/datagen/self_instruct/filter/instruction_filter.py
  camel/datagen/self_instruct/self_instruct.py
  docs/conf.py
  docs/cookbooks/agents_message.ipynb
  docs/cookbooks/agents_prompting.ipynb
  docs/cookbooks/agents_society.ipynb
  docs/cookbooks/agents_tracking.ipynb
  docs/cookbooks/agents_with_memory.ipynb
  docs/cookbooks/agents_with_rag.ipynb
  docs/cookbooks/agents_with_tools.ipynb
  docs/cookbooks/cot_data_gen_sft_qwen_unsolth_upload_huggingface.ipynb
  docs/cookbooks/cot_data_gen_upload_to_huggingface.ipynb
  docs/cookbooks/create_your_first_agent.ipynb
  docs/cookbooks/create_your_first_agents_society.ipynb
  docs/cookbooks/critic_agents_and_tree_search.ipynb
  docs/cookbooks/customer_service_Discord_bot_using_SambaNova_with_agentic_RAG.ipynb
  docs/cookbooks/customer_service_Discord_bot_using_local_model_with_agentic_RAG.ipynb
  docs/cookbooks/customer_service_Discord_bot_with_agentic_RAG.ipynb
  docs/cookbooks/embodied_agents.ipynb
  docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/cookbooks/knowledge_graph.ipynb
  docs/cookbooks/model_speed_comparison.ipynb
  docs/cookbooks/roleplaying_scraper.ipynb
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning_Qwen2_5_7B.ipynb
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning_mistral_7b_instruct.ipynb
  docs/cookbooks/sft_data_generation_and_unsloth_finetuning_tinyllama.ipynb
  docs/cookbooks/task_generation.ipynb
  docs/cookbooks/video_analysis.ipynb
  docs/cookbooks/workforce_judge_committee.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
Labels: bug

#1392 fix: update anthropic
  camel/configs/anthropic_config.py
  camel/models/anthropic_model.py
  camel/utils/token_counting.py
  examples/models/role_playing_with_claude.py
  poetry.lock
  pyproject.toml
Labels: bug

#1400 chore: Refinement of dependency management and improvement of related…
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#1419 doc & fix: Update tool calling benchmark examples and fix bugs
  camel/benchmarks/apibank.py
  camel/benchmarks/apibench.py
  examples/benchmarks/apibank.py
  examples/benchmarks/apibench.py
  examples/benchmarks/nexus.py
Labels: enhancement

#1429 fix: Infinite Loop in ChatAgent & & missing token in Discord
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/agents/chat_agent.py
  camel/bots/discord/discord_app.py
  poetry.lock
  test/bots/test_discord_app.py
  test/bots/test_slack_app.py
  test/bots/test_telegram_bot.py
Labels: bug

#1289 feat: Source2synth
  camel/agents/multi_hop_generator_agent.py
  camel/agents/programmed_agent_instruction.py
  camel/synthetic_datagen/source2synth/data_processor.py
  camel/synthetic_datagen/source2synth/models.py
  camel/synthetic_datagen/source2synth/user_data_processor_config.py
  examples/source2synth.py
Labels: New Feature

#1435 docs：optimize cotdata docs
  docs/cookbooks/model_training/cot_data_gen_sft_qwen_unsolth_upload_huggingface.ipynb
Labels: documentation

#1439 fix: camel app AttributeError
  apps/agents/agents.py
  apps/agents/test/test_agents.py
Labels: bug

#1440 feat: Add Free Proxies option into Google Scholar Toolkit
  camel/toolkits/google_scholar_toolkit.py
Labels: enhancement

#1446 fix: sample new instruction pool before updating the existing function
  camel/datagen/self_instruct/self_instruct.py
  camel/datagen/self_instruct/templates.py
Labels: bug

#1450 docs: Cookbook for dynamic travel planner
  README.md
  docs/cookbooks/applications/dynamic_travel_planner.ipynb
  docs/cookbooks/applications/index.rst
Labels: documentation

#1451 docs: Cookbook for self-instruct
  README.md
  docs/cookbooks/applications/index.rst
  docs/cookbooks/data_generation/cot_data_gen_sft_qwen_unsolth_upload_huggingface.ipynb
  docs/cookbooks/data_generation/data_gen_with_real_function_calls_and_hermes_format.ipynb
  docs/cookbooks/data_generation/index.rst
  docs/cookbooks/data_generation/self_instruct_data_generation.ipynb
  docs/cookbooks/data_generation/sft_data_generation_and_unsloth_finetuning_Qwen2_5_7B.ipynb
  docs/cookbooks/data_generation/sft_data_generation_and_unsloth_finetuning_mistral_7b_instruct.ipynb
  docs/cookbooks/data_generation/sft_data_generation_and_unsloth_finetuning_tinyllama.ipynb
  docs/cookbooks/model_training/cot_data_gen_upload_to_huggingface.ipynb
  docs/index.rst
Labels: documentation

#1449 fix: document link mapping issue to maintain access to old links
  docs/conf.py
  poetry.lock
  pyproject.toml
Labels: bug

#1332 docs: Reward model cookbook
  README.md
  docs/cookbooks/applications/dynamic_travel_planner.ipynb
  docs/cookbooks/data_generation/index.rst
  docs/cookbooks/data_generation/synthetic_dataevaluation&filter_with_reward_model.ipynb
  examples/models/reward/nemotron_model_example.py
Labels: documentation

#1358 docs: Qwen data-gen cookbook
  README.md
  docs/cookbooks/data_generation/data_model_generation_and_structured_output_with_qwen.ipynb
  docs/cookbooks/data_generation/index.rst
Labels: documentation

#1420 docs: human in the loop cookbook with HumanLayer
  README.md
  docs/cookbooks/advanced_features/agents_with_human_in_loop_and_tool_approval.ipynb
  docs/cookbooks/advanced_features/index.rst
Labels: cookbook

#1395 feat: structured loader
  camel/benchmarks/gaia.py
  camel/loaders/__init__.py
  camel/loaders/panda_reader.py
  docs/cookbooks/applications/dynamic_travel_planner.ipynb
  examples/loaders/panda_example.py
  poetry.lock
  pyproject.toml
  test/loaders/test_pandaai.py
Labels: New Feature

#1466 feat: Integrate InternLM models
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/internlm_config.py
  camel/models/__init__.py
  camel/models/internlm_model.py
  camel/models/model_factory.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/internlm_model_example.py
  test/models/test_internlm_model.py
Labels: Model, New Feature

#1436 feat: Update function call result message format
  camel/agents/chat_agent.py
  camel/data_collector/base.py
  camel/data_collector/sharegpt_collector.py
  camel/messages/__init__.py
  camel/messages/conversion/conversation_models.py
  camel/messages/func_message.py
  camel/models/cohere_model.py
  camel/models/mistral_model.py
  camel/types/__init__.py
  camel/types/enums.py
  camel/types/openai_types.py
  examples/data_collector/alpaca_collector.py
  examples/structured_response/structure_response_prompt_engineering.py
  test/data_collectors/test_sharegpt_collector.py
  test/messages/test_func_message.py
Labels: enhancement

#1468 release: v0.2.17
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
Labels: Release

#1469 fix: Gemini tool calling support
  camel/messages/func_message.py
  camel/models/gemini_model.py
  test/messages/test_func_message.py
Labels: enhancement

#1477 feat: Support SambaCloud and TogetherAI native tool call
  camel/types/enums.py
Labels: enhancement

#1484 fix: Recover the response_format setting in modelbackend
  camel/agents/chat_agent.py
Labels: bug

#1483 feat: Support getting reasoning content from deepseek r1
  camel/models/deepseek_model.py
  examples/models/deepseek_model_example.py
Labels: enhancement

#1480 fix: execute python code in unsafe mode
  camel/interpreters/internal_python_interpreter.py
  examples/interpreters/internal_python_interpreter.py
  test/interpreters/test_python_interpreter.py
Labels: bug

#1487 release: v0.2.18
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/cookbooks/data_generation/data_gen_with_real_function_calls_and_hermes_format.ipynb
  docs/cookbooks/data_generation/self_instruct_data_generation.ipynb
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
Labels: Release

#1500 feat: Integrate jina embedding
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/embeddings/__init__.py
  camel/embeddings/jina_embedding.py
  camel/types/enums.py
  examples/embeddings/jina_embedding_example.py
  test/embeddings/test_jina_embedding.py
Labels: New Feature, Embeddings

#1498 chore:add deepseek reasonr separate answer and deepseek chat model example
  examples/models/deepseek_chat_model_example.py
  examples/models/deepseek_reasoner_model_example.py
  examples/models/deepseek_reasoner_model_separate_answers.py
Labels: enhancement

#1464 feat: enhance source2synth
  README.md
  camel/agents/multi_hop_generator_agent.py
  camel/agents/programmed_agent_instruction.py
  camel/datagen/source2synth/__init__.py
  camel/datagen/source2synth/data_processor.py
  camel/datagen/source2synth/models.py
  camel/datagen/source2synth/user_data_processor_config.py
  examples/datagen/source2synth.py
Labels: enhancement

#1512 feat: Support tool calling for SGLang and Groq
  camel/configs/gemini_config.py
  camel/configs/sglang_config.py
  camel/models/groq_model.py
  camel/types/enums.py
  examples/models/role_playing_with_groq.py
Labels: enhancement

#1522 chore: openai version update and tool call message content converting
  camel/messages/func_message.py
  camel/models/openai_model.py
  camel/toolkits/search_toolkit.py
  examples/toolkits/openbb_toolkit.py
  poetry.lock
  pyproject.toml
  test/messages/test_func_message.py
Labels: bug

#1523 fix: Deepseek r1 reasoning content
  camel/models/deepseek_model.py
  examples/models/deepseek_reasoner_model_example.py
  examples/models/deepseek_reasoner_model_separate_answers.py
Labels: bug

#1514 enhance: STaR Integration
  camel/agents/chat_agent.py
  camel/datagen/__init__.py
  camel/datagen/star/star_pipeline.py
  camel/toolkits/reddit_toolkit.py
  camel/toolkits/whatsapp_toolkit.py
  camel/utils/__init__.py
  camel/utils/commons.py
  docs/camel.rst
  docs/key_modules/datagen.md
  examples/datagen/star/download_math500_dataset.py
  examples/datagen/star/math_500_dataset.json
  examples/datagen/star/star_example.py
  examples/datagen/star/star_example_with_r1.py
  examples/datagen/star/star_output.json
  examples/star_datagen/input_problems.json
  examples/star_datagen/star_example.py
  examples/star_datagen/star_output.json
  poetry.lock
  pyproject.toml
  test/datagen/star/test_star_pipeline.py
  test/utils/test_commons.py
Labels: enhancement

#1533 feat: Support OpenAI o3 mini
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/models/openai_model.py
  camel/types/enums.py
  camel/utils/token_counting.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  examples/models/openai_o1_example.py
  examples/models/openai_o3_mini_example.py
  pyproject.toml
Labels: Model
