Repository camel-ai/camel, pull requests merged in 2025-08, with the labels that each got.

#2986 feat: add metaso.cn API search
  .env
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
  test/toolkits/test_search_functions.py
Labels: Tool, Waiting for Update

#2939 docs: add structured output tutorial to agents.mdx (fixes #2900)
  docs/mintlify/key_modules/agents.mdx
Labels: Review Required

#2937 feat: Add TerminalToolkit MCP server and examples
  examples/toolkits/mcp/mcp_terminal_toolkit/client.py
  examples/toolkits/mcp/mcp_terminal_toolkit/terminal_toolkit_server.py
Labels: Review Required

#3025 feat: Update OpenAIImageToolkit to support multiple image generation
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/toolkits/openai_image_toolkit.py
  docs/conf.py
  docs/reference/camel.toolkits.openai_image_toolkit.md
  examples/toolkits/openai_image_example.py
  pyproject.toml
  uv.lock
Labels: enhancement

#3011 Optimise Task channel
  camel/societies/workforce/task_channel.py
  camel/societies/workforce/workforce.py
  examples/workforce/eigent.py
  test/workforce/test_workforce.py
Labels: enhancement, Review Required

#3038 chore: enhance toolkit function naming
  CONTRIBUTING.md
  camel/toolkits/github_toolkit.py
  camel/toolkits/math_toolkit.py
  camel/toolkits/search_toolkit.py
  docs/mintlify/reference/camel.toolkits.github_toolkit.mdx
  docs/mintlify/reference/camel.toolkits.search_toolkit.mdx
  docs/reference/camel.toolkits.github_toolkit.md
  docs/reference/camel.toolkits.search_toolkit.md
  examples/toolkits/github_toolkit.py
  test/agents/test_chat_agent.py
  test/toolkits/test_github_toolkit.py
Labels: enhancement

#2926 docs: Improvise Workforce
  docs/mintlify/docs.json
  docs/mintlify/key_modules/browsertoolkit.mdx
  docs/mintlify/key_modules/terminaltoolkit.mdx
  docs/mintlify/key_modules/workforce.mdx
Labels: Review Required

#2985 feat: add AMD model platform support
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/amd_config.py
  camel/models/__init__.py
  camel/models/amd_model.py
  camel/models/model_factory.py
  camel/types/enums.py
  examples/models/amd_model_example.py
  test/models/test_amd_model.py
Labels: Model, Waiting for Update

#3039 chore: enhance usage with stream mode
  camel/agents/chat_agent.py
  examples/agents/chatagent_stream.py
Labels: enhancement
