Repository camel-ai/camel, pull requests merged in 2025-02, with the labels that each got.

#1534 fix: WolframAlpha result from all subpods
  camel/datahubs/huggingface.py
  camel/toolkits/search_toolkit.py
  test/datahubs/test_huggingface.py
  test/embeddings/test_open_source_embeddings.py
  test/embeddings/test_vlm_embeddings.py
Labels: bug

#1532 docs:data distillation pipline for distilling high-quality maths reasoning data with thought process (Long Cot data)from deepseek R1
  README.md
  docs/cookbooks/data_generation/distill_math_reasoning_data_from_deepseek_r1.ipynb
  docs/cookbooks/data_generation/index.rst
Labels: Data, cookbook

#1526 feat: Integrate moonshot models to camel
  .env
  .github/workflows/build_package.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/moonshot_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/moonshot_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/moonshot_model_example.py
  test/models/test_moonshot_model.py
Labels: Model

#1556 docs: Add Self-Improving Math Reasoning Data Distillation
  README.md
  docs/cookbooks/data_generation/cot_data_gen_sft_qwen_unsolth_upload_huggingface.ipynb
  docs/cookbooks/data_generation/distill_math_reasoning_data_from_deepseek_r1.ipynb
  docs/cookbooks/data_generation/index.rst
  docs/cookbooks/data_generation/self_improving_math_reasoning_data_distillation_from_deepSeek_r1.ipynb
  docs/cookbooks/data_generation/synthetic_dataevaluation&filter_with_reward_model.ipynb
Labels: cookbook

#1541 feat: Integrate siliconflow model
  .github/workflows/build_package.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  camel/configs/__init__.py
  camel/configs/siliconflow_config.py
  camel/embeddings/jina_embedding.py
  camel/models/model_factory.py
  camel/models/siliconflow_model.py
  camel/types/enums.py
  examples/models/siliconflow_model_example.py
Labels: Model

#1557 chore: Update supported models
  camel/types/enums.py
  docs/key_modules/models.md
  examples/models/gemini_model_example.py
  test/models/test_gemini_model.py
  test/models/test_zhipuai_model.py
Labels: Model

#1558 chore: Support Gemini 2.0 flash thinking and pro
  camel/types/enums.py
  examples/models/gemini_model_example.py
  test/models/test_gemini_model.py
Labels: Model

#1492 chore: Rename tool call instances
  camel/agents/chat_agent.py
  examples/models/openai_o3_mini_example.py
  examples/models/role_playing_with_cohere.py
  examples/models/role_playing_with_mistral.py
  examples/models/role_playing_with_ollama.py
  examples/models/role_playing_with_sambanova.py
  examples/observability/agentops_track_roleplaying_with_function.py
  examples/toolkits/arxiv_toolkit.py
  examples/toolkits/google_scholar_toolkit.py
  examples/toolkits/notion_toolkit.py
  examples/toolkits/openapi_toolkit.py
  examples/toolkits/role_playing_with_functions.py
  test/agents/test_chat_agent.py
Labels: enhancement

#1493 feat: Add SemanticScholarToolkits to integrate Semantic Scholar to camel
  camel/toolkits/__init__.py
  camel/toolkits/semanticscholar_toolkit.py
  examples/toolkits/semanticscholar_toolkit.py
  test/toolkits/test_semantic_functions.py
Labels: New Feature

#1508 enhance: SymPy toolkit integration
  camel/toolkits/sympy_toolkit.py
  examples/toolkits/sympy_toolkit.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1564 release: v0.2.20a0
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/toolkits/semantic_scholar_toolkit.py
  camel/types/enums.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
  test/models/test_qwen_model.py
  test/toolkits/test_semantic_scholar_functions.py
Labels: Release

#1566 release: 0.2.20a1
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/types/enums.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
  test/models/test_qwen_model.py
Labels: Release

#1445 feat: Waleed Sympy integration
  camel/toolkits/__init__.py
  camel/toolkits/sympy_toolkit.py
  camel/utils/__init__.py
  camel/utils/token_counting.py
  examples/toolkits/sympy_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_semantic_scholar_functions.py
  test/toolkits/test_sympy_toolkit.py
Labels: New Feature

#1478 feat: implementing STaR: Self Taught Reasoner
  camel/agents/chat_agent.py
  camel/datagen/__init__.py
  camel/datagen/cot_datagen.py
  camel/datagen/self_improving_cot.py
  camel/toolkits/reddit_toolkit.py
  camel/toolkits/whatsapp_toolkit.py
  camel/types/enums.py
  camel/utils/__init__.py
  camel/utils/commons.py
  docs/camel.rst
  docs/cookbooks/data_generation/index.rst
  docs/cookbooks/data_generation/self_improving_cot_generation.md
  docs/key_modules/datagen.md
  examples/datagen/self_improving_cot/download_math_datasets.py
  examples/datagen/self_improving_cot/gsm8k_dataset.json
  examples/datagen/self_improving_cot/self_improving_cot_example.py
  examples/datagen/self_improving_cot/self_improving_cot_example_with_r1.py
  poetry.lock
  pyproject.toml
  test/datagen/test_self_improving_cot_pipeline.py
  test/utils/test_commons.py
Labels: New Feature

#1572 chore: Issue&PR template and dependency update
  .github/PULL_REQUEST_TEMPLATE.md
  camel/benchmarks/ragbench.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1574 docs(cookbooks): Fix Unused Custom Tool in Tools Cookbook (issue-1573)
  docs/cookbooks/advanced_features/agents_with_tools.ipynb
Labels: bug

#1568 feat: Internal deduplication impl.
  camel/utils/__init__.py
  camel/utils/deduplication.py
  pyproject.toml
  test/utils/test_deduplication.py
Labels: New Feature

#1579 refactor: Internal deduplication
  camel/utils/deduplication.py
  test/utils/test_deduplication.py
Labels: enhancement

#1586 chore: update unstructured io version
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#1590 fix: Subprocess interpreter don't have output
  camel/interpreters/subprocess_interpreter.py
  pyproject.toml
  test/prompts/test_prompt_base.py
Labels: bug

#1593 feat: URL Handling in OpenAIEmbedding to Align with OpenAIModel
  camel/embeddings/openai_embedding.py
Labels: enhancement

#1599 chore: Small enhancement and fix
  camel/interpreters/docker/Dockerfile
  camel/interpreters/docker_interpreter.py
  camel/interpreters/subprocess_interpreter.py
  camel/toolkits/sympy_toolkit.py
  docs/index.rst
  docs/key_modules/agents.md
  docs/key_modules/datagen.md
  examples/ai_society/babyagi_playing.py
  examples/bots/discord_bot.py
  examples/bots/discord_bot_use_msg_queue.py
  examples/bots/slack_bot.py
  examples/bots/slack_bot_use_msg_queue.py
  examples/models/role_playing_with_sambanova.py
  examples/structured_response/structure_response_prompt_engineering.py
  test/interpreters/test_docker_interpreter.py
  test/interpreters/test_subprocess_interpreter.py
  test/prompts/test_prompt_base.py
Labels: enhancement

#1529 feat: adding MinerU Extractor
  .env
  camel/loaders/__init__.py
  camel/loaders/mineru_extractor.py
  camel/toolkits/__init__.py
  camel/toolkits/mineru_toolkit.py
  examples/loaders/mineru_example.py
  examples/toolkits/mineru_toolkit.py
  test/loaders/test_mineru_extractor.py
  test/toolkits/test_mineru_toolkit.py
Labels: Loader

#1612 feat(datagen): Enhance JSON Dump in SelfInstructPipeline for Non-ASCII Character Readability
  camel/datagen/self_instruct/self_instruct.py
Labels: enhancement

#1613 fix: Remove <think> content in model request
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/models/base_model.py
  camel/models/deepseek_model.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  pyproject.toml
  test/models/test_base_model.py
Labels: bug

#1617 docs: Correct hyperlink for Hackathon Judge Committee
  docs/key_modules/workforce.md
Labels: bug

#1610 docs(cookbooks): Fix incorrect URL in self_instruct_data_generation.ipynb
  docs/cookbooks/data_generation/self_instruct_data_generation.ipynb
Labels: bug, cookbook

#1605 feat: custom prompt in graph agent
  camel/agents/knowledge_graph_agent.py
  examples/knowledge_graph/knowledge_graph_agent_example.py
Labels: enhancement

#1577 refactor: NetworkX integration
  camel/benchmarks/ragbench.py
  camel/storages/graph_storages/Networkx.py
  camel/toolkits/__init__.py
  camel/toolkits/networkx_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_networkx_toolkit.py
Labels: enhancement

#1398 feat: Hybrid Retrieval
  camel/retrievers/__init__.py
  camel/retrievers/hybrid_retrival.py
  examples/rag/single_agent_with_hybrid_rag.py
  test/retrievers/test_hybrid_retriever.py
Labels: New Feature

#1456 feat: Waleed Networkx integration
  camel/toolkits/__init__.py
  camel/toolkits/networkx_toolkit.py
  examples/toolkits/networkx_toolkit.py
  poetry.lock
  pyproject.toml
  test/toolkits/test_networkx_toolkit.py
Labels: New Feature

#1424 refactor: ChatAgent
  camel/agents/_types.py
  camel/agents/_utils.py
  camel/agents/chat_agent.py
  camel/agents/multi_hop_generator_agent.py
  camel/configs/base_config.py
  camel/configs/deepseek_config.py
  camel/configs/gemini_config.py
  camel/configs/openai_config.py
  camel/configs/qwen_config.py
  camel/messages/base.py
  camel/models/_utils.py
  camel/models/aiml_model.py
  camel/models/anthropic_model.py
  camel/models/azure_openai_model.py
  camel/models/base_model.py
  camel/models/cohere_model.py
  camel/models/deepseek_model.py
  camel/models/gemini_model.py
  camel/models/groq_model.py
  camel/models/internlm_model.py
  camel/models/litellm_model.py
  camel/models/mistral_model.py
  camel/models/model_manager.py
  camel/models/moonshot_model.py
  camel/models/nemotron_model.py
  camel/models/nvidia_model.py
  camel/models/ollama_model.py
  camel/models/openai_audio_models.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  camel/models/qwen_model.py
  camel/models/reka_model.py
  camel/models/samba_model.py
  camel/models/sglang_model.py
  camel/models/siliconflow_model.py
  camel/models/stub_model.py
  camel/models/togetherai_model.py
  camel/models/vllm_model.py
  camel/models/yi_model.py
  camel/models/zhipuai_model.py
  camel/toolkits/function_tool.py
  camel/types/__init__.py
  camel/types/agents/__init__.py
  camel/types/agents/tool_calling_record.py
  camel/types/openai_types.py
  camel/utils/__init__.py
  camel/utils/async_func.py
  camel/utils/commons.py
  examples/models/nemotron_model_example.py
  examples/toolkits/role_playing_with_functions.py
  poetry.lock
  test/agents/test_chat_agent.py
  test/models/test_base_model.py
  test/models/test_model_factory.py
Labels: Refactor

#1594 feat: Integrate Zapier AI tool
  camel/toolkits/__init__.py
  camel/toolkits/zapier_toolkit.py
  examples/toolkits/zapier_toolkit.py
  test/toolkits/test_zapier_ai_function.py
Labels: New Feature

#1591 feat: add warning
  camel/memories/agent_memories.py
  camel/memories/context_creators/score_based.py
Labels: enhancement

#1567 docs: Update documentation for models
  docs/key_modules/models.md
Labels: documentation, enhancement

#1624 fix: Backend model tool call
  camel/agents/_utils.py
  camel/models/_utils.py
  camel/models/aiml_model.py
  camel/models/groq_model.py
  camel/models/moonshot_model.py
  camel/models/ollama_model.py
  camel/models/qwen_model.py
Labels: bug

#1615 docs: Unify cookbooks of basic concepts
  docs/cookbooks/basic_concepts/agents_message.ipynb
  docs/cookbooks/basic_concepts/agents_prompting.ipynb
  docs/cookbooks/basic_concepts/create_your_first_agent.ipynb
  docs/cookbooks/basic_concepts/create_your_first_agents_society.ipynb
  docs/cookbooks/basic_concepts/model_speed_comparison.ipynb
  docs/cookbooks/data_generation/self_instruct_data_generation.ipynb
  docs/cookbooks/data_processing/agent_with_chunkr_for_pdf_parsing.ipynb
Labels: documentation

#1630 feat: Add api key link in error info
  camel/utils/commons.py
Labels: enhancement

#1627 feat(datagen): add stop_on_first_failure option to InstructionFilter
  camel/datagen/self_instruct/filter/instruction_filter.py
  camel/datagen/self_instruct/self_instruct.py
  test/datagen/self_instruct/filter/instruction_filter_tests.py
Labels: enhancement

#1633 fix: Base model handle image type
  camel/models/base_model.py
  camel/utils/commons.py
  test/models/test_base_model.py
Labels: bug

#1631 test: Update anthropic model unit test for refactored model backend
  test/models/test_anthropic_model.py
Labels: Test

#1629 feat: KnowNo implementation
  camel/agents/chat_agent.py
  examples/agent/agent_step_with_reasoning.py
Labels: New Feature

#1645 docs: Unify Data Processing Cookbooks
  docs/cookbooks/basic_concepts/agents_prompting.ipynb
  docs/cookbooks/data_processing/agent_with_chunkr_for_pdf_parsing.ipynb
  docs/cookbooks/data_processing/ingest_data_from_websites_with_Firecrawl.ipynb
  docs/cookbooks/data_processing/video_analysis.ipynb
Labels: enhancement, cookbook

#1657 fix: Keep `strict` in tool schema
  camel/models/openai_model.py
  test/datahubs/test_huggingface.py
Labels: bug

#1620 feat: Initial implementation for env, dataset, extractor base model
  camel/datasets/base.py
  camel/environments/base.py
  camel/extractors/base.py
  camel/verifiers/base.py
Labels: New Feature, Loong
