Repository camel-ai/camel, pull requests merged in 2025-03, with the labels that each got.

#1673 feat:add gpt4.5 model
  camel/types/enums.py
  docs/key_modules/models.md
  examples/models/openai_gpt_4.5_preview_example.py
  test/models/test_openai_model.py
Labels: Model

#1644 feat(memories): add timestamp in VectorDBMemory to prevent data retrieval order confusion
  camel/memories/agent_memories.py
  camel/memories/blocks/chat_history_block.py
  camel/memories/blocks/vectordb_block.py
  camel/memories/context_creators/score_based.py
  camel/memories/records.py
  test/memories/context_creators/test_score_based.py
  test/memories/test_blocks.py
  test/memories/test_vector_db_memory.py
Labels: bug

#1676 test: updated cohere test by adding async tests
  test/models/test_cohere_model.py
Labels: Test

#1597 feat: Initial implementation for BaseVerifier
  camel/datasets/__init__.py
  camel/datasets/base.py
  camel/environments/__init__.py
  camel/environments/base.py
  camel/extractors/__init__.py
  camel/extractors/base.py
  camel/verifiers/__init__.py
  camel/verifiers/base.py
  camel/verifiers/models.py
  test/datasets/test_base_dataset.py
  test/environments/test_base_env.py
  test/extractors/test_base_extractor.py
  test/verifiers/test_base_verifier.py
Labels: New Feature

#1702 feat: Python Verifier implementation
  camel/verifiers/__init__.py
  camel/verifiers/models.py
  camel/verifiers/python_verifier.py
  examples/verifier/python_verifier_example.py
  test/verifiers/test_python_verifier.py
Labels: New Feature, Loong

#1651 chore: Remove heavy & unnecessary dependencies
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/models/sglang_model.py
  camel/toolkits/ask_news_toolkit.py
  camel/toolkits/openbb_toolkit.py
  docs/conf.py
  docs/get_started/installation.md
  docs/key_modules/loaders.md
  poetry.lock
  pyproject.toml
  test/datagen/test_self_improving_cot_pipeline.py
  test/toolkits/test_asknews_function.py
  test/toolkits/test_openbb_functions.py
Labels: enhancement

#1719 chore: Update ModelManager error message for one model
  camel/agents/chat_agent.py
  camel/models/model_manager.py
Labels: enhancement

#1718 feat(datagen): Enhance JSON output with ensure_ascii option in SelfImprovingCoTPipeline
  camel/datagen/self_improving_cot.py
Labels: enhancement

#1743 docs: Update doc
  docs/camel.benchmarks.rst
  docs/camel.bots.discord.rst
  docs/camel.bots.rst
  docs/camel.bots.slack.rst
  docs/camel.data_collector.rst
  docs/camel.datagen.rst
  docs/camel.datagen.self_instruct.filter.rst
  docs/camel.datagen.self_instruct.rst
  docs/camel.datagen.source2synth.rst
  docs/camel.datahubs.rst
  docs/camel.datasets.rst
  docs/camel.environments.rst
  docs/camel.extractors.rst
  docs/camel.messages.conversion.rst
  docs/camel.messages.conversion.sharegpt.hermes.rst
  docs/camel.messages.conversion.sharegpt.rst
  docs/camel.models.reward.rst
  docs/camel.personas.rst
  docs/camel.runtime.rst
  docs/camel.runtime.utils.rst
  docs/camel.schemas.rst
  docs/camel.types.agents.rst
  docs/camel.verifiers.rst
  docs/cookbooks/data_generation/synthetic_dataevaluation&filter_with_reward_model.ipynb
  docs/images/workforce2.png
Labels: bug, documentation

#1741 feat: add image analysis toolkit
  camel/toolkits/__init__.py
  camel/toolkits/image_analysis_toolkit.py
  examples/toolkits/image_analysis_toolkit.py
  test/toolkits/test_image_analysis_toolkiy.py
Labels: New Feature

#1740 feat: Add video analysis toolkit
  camel/toolkits/__init__.py
  camel/toolkits/video_analysis_toolkit.py
  camel/toolkits/video_download_toolkit.py
  pyproject.toml
  test/toolkits/test_video_function.py
Labels: New Feature

#1745 feat: Update dependency management to uv
  .container/Dockerfile
  .container/minimal_build/Dockerfile
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/camel_install/action.yml
  .github/workflows/build_package.yml
  .github/workflows/documentation.yml
  .github/workflows/pre_commit.yml
  .github/workflows/publish_release.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  CONTRIBUTING.md
  INSTALLATION.md
  README.md
  docs/get_started/installation.md
  examples/models/sglang_model_example.py
  examples/toolkits/role_playing_with_functions.py
  poetry.lock
  pyproject.toml
  uv.lock
Labels: Dependency, New Feature

#1749 chore: Update uv install
  .container/Dockerfile
  .container/minimal_build/Dockerfile
  .github/actions/camel_install/action.yml
  .github/workflows/build_package.yml
  .github/workflows/publish_release.yml
  .github/workflows/pytest_apps.yml
  .github/workflows/pytest_package.yml
  CONTRIBUTING.md
  docs/get_started/installation.md
Labels: bug

#1739 feat: Add ExcelToolkit
  .github/workflows/documentation.yml
  camel/toolkits/__init__.py
  camel/toolkits/excel_toolkit.py
  camel/toolkits/video_analysis_toolkit.py
  camel/toolkits/video_download_toolkit.py
  examples/toolkits/excel_toolkit.py
  examples/toolkits/video_analysis_toolkit.py
  pyproject.toml
  test/toolkits/test_excel_toolkit.py
  test/toolkits/test_video_analysis_toolkit.py
  test/toolkits/test_video_download_function.py
  uv.lock
Labels: New Feature

#1744 feat: Add audio toolkit from owl project
  .pre-commit-config.yaml
  camel/models/__init__.py
  camel/models/base_audio_model.py
  camel/models/fish_audio_model.py
  camel/models/openai_audio_models.py
  camel/toolkits/__init__.py
  camel/toolkits/audio_analysis_toolkit.py
  examples/toolkits/audio_analysis_toolkit.py
  test/models/test_fish_audio_model.py
  test/toolkits/test_audio_analysis_toolkit.py
  test/toolkits/test_open_api_function.py
Labels: New Feature

#1751 feat: Add WebToolkit from owl
  camel/toolkits/__init__.py
  camel/toolkits/page_script.js
  camel/toolkits/web_toolkit.py
  examples/toolkits/web_toolkit.py
  pyproject.toml
  uv.lock
Labels: New Feature

#1750 fix: issues about local image path
  camel/toolkits/image_analysis_toolkit.py
Labels: bug

#1753 release: version 0.2.23
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: Release

#1758 fix: Update web_toolkit.py
  camel/toolkits/web_toolkit.py
Labels: bug

#1759 feat: Terminal Toolkit
  camel/toolkits/__init__.py
  camel/toolkits/terminal_toolkit.py
  docs/key_modules/tools.md
  examples/toolkits/terminal_toolkit.py
  test/toolkits/test_terminal_toolkit.py
Labels: New Feature

#1755 feat: integrate MCP client as a Toolkit
  camel/toolkits/__init__.py
  camel/toolkits/mcp_toolkit.py
  examples/toolkits/mcp/mcp_server.py
  examples/toolkits/mcp/mcp_toolkit.py
  pyproject.toml
  test/toolkits/test_mcp_toolkit.py
  uv.lock
Labels: New Feature

#1688 feat: Update anthropic config and integrate Claude 3.7
  camel/configs/anthropic_config.py
  camel/models/anthropic_model.py
  camel/types/enums.py
  examples/models/anthiropic_model_example.py
Labels: enhancement

#1774 feat: Add file write toolkit
  camel/toolkits/__init__.py
  camel/toolkits/file_write_toolkit.py
  examples/toolkits/file_write_toolkit.py
  pyproject.toml
  test/toolkits/test_file_write_toolkit.py
  uv.lock
Labels: New Feature

#1787 feat: RolePlaying support async run
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/societies/role_playing.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  test/agents/test_role_playing.py
  uv.lock
Labels: New Feature, Release

#1742 refactor: Implement extraction as strategy pattern
  camel/environments/base.py
  camel/extractors/__init__.py
  camel/extractors/base.py
  camel/extractors/python_strategies.py
  examples/extractors/python_strategies_example.py
  pyproject.toml
  test/extractors/test_base_extractor.py
  test/extractors/test_python_strategies.py
Labels: Refactor, Loong

#1809 refactor: Updat base dataset PR
  camel/datasets/base.py
Labels: enhancement, Loong

#1734 refactor Seed Dataset to improve compatibility and simplify usage
  camel/datasets/base.py
  test/datasets/test_base_dataset.py
Labels: enhancement, Refactor, P0, Loong

#1806 fead: Add pubmed in toolkits
  camel/toolkits/__init__.py
  camel/toolkits/pubmed_toolkit.py
  examples/toolkits/pubmed_toolkit.py
  test/toolkits/test_pubmed_toolkit.py
Labels: New Feature

#1799 feat: Add Claude tool calling
  camel/agents/chat_agent.py
  camel/configs/anthropic_config.py
  camel/models/anthropic_model.py
  examples/models/anthiropic_model_example.py
Labels: enhancement

#1795 fix: add py.typed marker for PEP 561 type hint support
  camel/py.typed
Labels: enhancement

#1811 release: version 0.2.26
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: Release

#1820 [refactor 1/n] Web toolkit
  camel/toolkits/web_toolkit.py
Labels: Refactor

#1804 feat: Add bocha search in search toolkit
  .env
  camel/toolkits/search_toolkit.py
  examples/toolkits/search_toolkit.py
  test/toolkits/test_search_functions.py
Labels: New Feature

#1817 feat: add MCPToolkitManager to manage multiple MCPToolkits.
  camel/toolkits/__init__.py
  camel/toolkits/mcp_toolkit.py
  examples/toolkits/mcp/mcp_server.py
  examples/toolkits/mcp/mcp_servers_config.json
  examples/toolkits/mcp/mcp_toolkit.py
  test/toolkits/test_mcp_toolkit.py
Labels: New Feature

#1835 release: 0.2.28
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: Release

#1801 refactor: Split dataset into 'StaticDataset' and 'GenerativeDataset'
  camel/datasets/__init__.py
  camel/datasets/base.py
  camel/environments/base.py
  examples/dataset/generative_dataset.py
  test/datasets/test_base_dataset.py
Labels: enhancement, Refactor

#1841 feat: Agent tool call try expect, update image log
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/chat_agent.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: enhancement

#1837 chore: enhance base dataset for loong
  camel/datasets/__init__.py
  camel/datasets/base.py
  camel/datasets/base_generator.py
  camel/datasets/models.py
  camel/datasets/static_dataset.py
  camel/environments/single_step.py
  examples/dataset/generative_dataset.py
  test/datasets/test_base_dataset.py
Labels: enhancement, Loong

#1856 feat: add baidu search
  camel/toolkits/search_toolkit.py
  docs/key_modules/tools.md
  examples/toolkits/search_toolkit.py
  pyproject.toml
  test/toolkits/test_search_functions.py
  uv.lock
Labels: New Feature, OWL

#1845 feat: Enhanced BrowserToolkit
  camel/toolkits/browser_toolkit.py
Labels: enhancement

#1862 release: v 0.2.30
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: Release

#1873 fix: add ensure_ascii to json dump
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/_utils.py
  camel/benchmarks/apibank.py
  camel/benchmarks/apibench.py
  camel/benchmarks/gaia.py
  camel/benchmarks/nexus.py
  camel/data_collector/sharegpt_collector.py
  camel/datahubs/huggingface.py
  camel/datasets/base_generator.py
  camel/loaders/base_io.py
  camel/loaders/chunkr_reader.py
  camel/messages/conversion/conversation_models.py
  camel/messages/func_message.py
  camel/models/cohere_model.py
  camel/models/samba_model.py
  camel/personas/persona.py
  camel/runtime/api.py
  camel/runtime/docker_runtime.py
  camel/runtime/remote_http_runtime.py
  camel/storages/key_value_storages/json.py
  camel/storages/key_value_storages/redis.py
  camel/toolkits/file_write_toolkit.py
  camel/toolkits/linkedin_toolkit.py
  camel/toolkits/networkx_toolkit.py
  camel/toolkits/search_toolkit.py
  camel/toolkits/semantic_scholar_toolkit.py
  camel/toolkits/stripe_toolkit.py
  camel/toolkits/sympy_toolkit.py
  camel/types/enums.py
  docs/conf.py
  docs/key_modules/loaders.md
  examples/ai_society/role_playing_multiprocess.py
  examples/code/role_playing_multiprocess.py
  examples/data_collector/sharegpt_collector.py
  examples/deductive_reasoner_agent/deduce_conditions_and_quality.py
  examples/evaluation/single_agent.py
  examples/generate_text_embedding_data/single_agent.py
  examples/misalignment/role_playing_multiprocess.py
  examples/summarization/gpt_solution_extraction.py
  examples/summarization/gpt_solver.py
  pyproject.toml
  test/datahubs/test_huggingface.py
  test/models/test_qwen_model.py
  uv.lock
Labels: bug

#1898 fix: GithubToolkit: Accept "Reference already exists" error
  camel/toolkits/github_toolkit.py
Labels: bug

#1891 chore: windows compactibility flag for mypy
  camel/models/sglang_model.py
  camel/toolkits/github_toolkit.py
Labels: bug

#1906 fix: postprocessing error for yt-dlp by sanitizing file names in FileWriteToolkit
  camel/toolkits/file_write_toolkit.py
  test/toolkits/test_file_write_toolkit.py
Labels: bug

#1904 fix cookbook link + missing import for tools section
  docs/cookbooks/basic_concepts/create_your_first_agent.ipynb
  docs/get_started/installation.md
  docs/key_modules/memory.md
  docs/key_modules/retrievers.md
  docs/key_modules/tasks.md
  docs/key_modules/tools.md
Labels: bug, documentation

#1903 fix: 2 typos in README.md
  README.md
Labels: documentation

#1913 release: version 0.2.34
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/knowledge_graph_agent.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: Release

#1900 refactor: Iterable dataset
  camel/datasets/base_generator.py
  test/datasets/test_base_dataset.py
Labels: Refactor, Loong

#1726 feat: Link memory to agent with id
  camel/agents/chat_agent.py
  camel/memories/agent_memories.py
  camel/memories/base.py
  camel/memories/records.py
  camel/storages/key_value_storages/__init__.py
  camel/storages/key_value_storages/json.py
  camel/storages/vectordb_storages/base.py
  camel/toolkits/__init__.py
  camel/toolkits/memory_toolkit.py
  examples/memories/agent_memory_example.py
  examples/memories/agent_memory_vector_db_example.py
  examples/memories/vector_db_memory_example.py
  examples/toolkits/memory_toolkit.py
  test/agents/test_chat_agent.py
  test/memories/test_agent_memories.py
  test/memories/test_blocks.py
  test/memories/test_chat_history_memory.py
  test/memories/test_vector_db_memory.py
  test/toolkits/test_memory_toolkit.py
Labels: New Feature, Memory

#1928 fix: Record all tool calls from LLM response
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  camel/agents/_types.py
  camel/agents/_utils.py
  camel/agents/chat_agent.py
  camel/configs/openai_config.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  test/agents/test_chat_agent.py
  uv.lock
Labels: bug

#1727 feat: Chunker module enabling custom chunking strategy
  camel/models/stub_model.py
  camel/retrievers/vector_retriever.py
  camel/utils/chunker/__init__.py
  camel/utils/chunker/base.py
  camel/utils/chunker/code_chunker.py
  camel/utils/chunker/uio_chunker.py
  camel/utils/token_counting.py
Labels: enhancement, New Feature

#1794 fix(storages): Replace deprecated `search` method with `query_points`
  camel/storages/vectordb_storages/qdrant.py
  test/loaders/test_pandaai.py
Labels: enhancement

#1933 chore: make the default selection for sanbox to subprocess in the Code_execution Toolkit.
  camel/toolkits/code_execution.py
Labels: enhancement

#1938 docs: update latest docs with missing toolkits
  docs/key_modules/tools.md
Labels: documentation

#1939 feat: accepting header in mcp toolkits
  camel/toolkits/mcp_toolkit.py
Labels: enhancement

#1796 feat: Integrate Mem0 as Memory
  camel/memories/agent_memories.py
  camel/storages/__init__.py
  camel/storages/key_value_storages/__init__.py
  camel/storages/key_value_storages/mem0_cloud.py
  docs/key_modules/memory.md
  pyproject.toml
  test/storages/key_value_storages/test_mem0_cloud.py
  uv.lock
Labels: New Feature

#1917 feat: adding support for openrouter
  camel/configs/__init__.py
  camel/configs/openrouter_config.py
  camel/models/__init__.py
  camel/models/model_factory.py
  camel/models/openrouter_model.py
  camel/types/enums.py
  camel/types/unified_model_type.py
  docs/key_modules/models.md
  examples/models/openrouter_model_example.py
  test/models/test_openrouter_model.py
Labels: New Feature

#1943 fix: mem0 mypy test and doc, openrouter key, mcp test
  .github/workflows/build_package.yml
  .github/workflows/pytest_package.yml
  camel/memories/agent_memories.py
  camel/memories/blocks/chat_history_block.py
  camel/storages/key_value_storages/mem0_cloud.py
  pyproject.toml
  test/storages/key_value_storages/test_mem0_cloud.py
  test/toolkits/test_code_execution.py
  test/toolkits/test_mcp_toolkit.py
Labels: bug

#1948 fix: remove anyOf to support Gemini tool call
  camel/models/gemini_model.py
Labels: bug

#1947 chore: Update all the model config parameters as optional and set default value as None.
  camel/configs/aiml_config.py
  camel/configs/anthropic_config.py
  camel/configs/cohere_config.py
  camel/configs/deepseek_config.py
  camel/configs/gemini_config.py
  camel/configs/groq_config.py
  camel/configs/internlm_config.py
  camel/configs/litellm_config.py
  camel/configs/mistral_config.py
  camel/configs/moonshot_config.py
  camel/configs/nvidia_config.py
  camel/configs/ollama_config.py
  camel/configs/openai_config.py
  camel/configs/openrouter_config.py
  camel/configs/qwen_config.py
  camel/configs/reka_config.py
  camel/configs/samba_config.py
  camel/configs/sglang_config.py
  camel/configs/siliconflow_config.py
  camel/configs/togetherai_config.py
  camel/configs/vllm_config.py
  camel/configs/yi_config.py
  camel/configs/zhipuai_config.py
Labels: enhancement

#1958 feat: add think toolkit
  camel/toolkits/__init__.py
  camel/toolkits/thinking_toolkit.py
  examples/toolkits/thinking_toolkit.py
  test/toolkits/test_thinking_toolkit.py
Labels: New Feature

#1971 enhance: Add cookbook for how to use SingleStepEnv PR1922
  camel/datasets/static_dataset.py
  camel/environments/single_step.py
  camel/extractors/__init__.py
  camel/verifiers/python_verifier.py
Labels: Loong

#1922 docs: Add cookbook for how to use `SingleStepEnv`
  camel/datasets/static_dataset.py
  camel/environments/models.py
  camel/environments/single_step.py
  camel/extractors/__init__.py
  camel/verifiers/base.py
  camel/verifiers/python_verifier.py
  examples/environments/demo.ipynb
  examples/verifier/python_verifier_example.py
  test/datasets/test_base_dataset.py
  test/environments/test_multi_step_env.py
  test/environments/test_single_stage_env.py
  test/verifiers/test_base_verifier.py
  test/verifiers/test_python_verifier.py
Labels: bug, cookbook

#1973 docs: improve cookbook for SingleStepEnv and add cookbook for batched SingleStepEnv
  camel/environments/single_step.py
  camel/verifiers/python_verifier.py
  docs/cookbooks/loong/batched_single_step_env.ipynb
  docs/cookbooks/loong/single_step_env.ipynb
Labels: cookbook, Loong

#1941 feat: A new agent that could process queries based on GitHub repos
  camel/agents/__init__.py
  camel/agents/repo_agent.py
  camel/utils/chunker/code_chunker.py
  examples/agent/repo_agent.py
  test/agents/test_repo_agent.py
Labels: New Feature

#1990 feat: add Evol-Instruct alike methods to camel/datagen
  camel/datagen/evol_instruct/__init__.py
  camel/datagen/evol_instruct/evol_instruct.py
  camel/datagen/evol_instruct/scorer.py
  camel/datagen/evol_instruct/templates.py
  examples/datagen/evol_instruct/evol_instruct.py
  examples/datagen/evol_instruct/input.json
  examples/datagen/evol_instruct/results.json
  test/datagen/test_evol_instruct.py
Labels: New Feature, Loong

#1942 feat: add tidb vector storage
  camel/retrievers/auto_retriever.py
  camel/storages/__init__.py
  camel/storages/vectordb_storages/__init__.py
  camel/storages/vectordb_storages/tidb.py
  camel/types/enums.py
  docs/camel.storages.vectordb_storages.rst
  docs/get_started/installation.md
  docs/key_modules/storages.md
  examples/storages/tidb_vector_storage.py
  pyproject.toml
  test/storages/vector_storages/test_tidb.py
Labels: New Feature, RAG

#1994 refactor: Thinking toolkit
  camel/toolkits/thinking_toolkit.py
  examples/toolkits/thinking_toolkit.py
  test/toolkits/test_thinking_toolkit.py
Labels: Refactor

#1937 feat: Support browser toolkit with pre-defined dynamic channel
  camel/toolkits/__init__.py
  camel/toolkits/browser_toolkit.py
  examples/toolkits/web_toolkit.py
  test/toolkits/test_browser_toolkit.py
Labels: New Feature

#1963 feat: add searxng toolkit
  camel/toolkits/__init__.py
  camel/toolkits/searxng_toolkit.py
  examples/toolkits/searxng_toolkit_example.py
  test/toolkits/test_searxng_toolkit.py
Labels: New Feature

#1953 feat: adding timeout for basemodel backend
  camel/models/aiml_model.py
  camel/models/anthropic_model.py
  camel/models/azure_openai_model.py
  camel/models/base_audio_model.py
  camel/models/base_model.py
  camel/models/deepseek_model.py
  camel/models/gemini_model.py
  camel/models/groq_model.py
  camel/models/internlm_model.py
  camel/models/model_factory.py
  camel/models/moonshot_model.py
  camel/models/nemotron_model.py
  camel/models/nvidia_model.py
  camel/models/ollama_model.py
  camel/models/openai_audio_models.py
  camel/models/openai_compatible_model.py
  camel/models/openai_model.py
  camel/models/openrouter_model.py
  camel/models/qwen_model.py
  camel/models/samba_model.py
  camel/models/sglang_model.py
  camel/models/siliconflow_model.py
  camel/models/stub_model.py
  camel/models/togetherai_model.py
  camel/models/vllm_model.py
  camel/models/yi_model.py
  camel/models/zhipuai_model.py
Labels: enhancement

#1824 feat: add openai response api
  camel/toolkits/__init__.py
  camel/toolkits/openai_agent_toolkit.py
  examples/toolkits/openai_agent_toolkit_example.py
  pyproject.toml
  test/toolkits/test_openai_agent_toolkit.py
  uv.lock
Labels: New Feature

#2023 refactor: Pandasai not using llm by default
  camel/loaders/__init__.py
  camel/loaders/pandas_reader.py
  examples/loaders/pandas_example.py
  test/loaders/test_pandaai.py
  test/loaders/test_pandasai.py
Labels: enhancement

#1788 fix: memory sort without system message
  camel/memories/context_creators/score_based.py
  examples/memory/score_based_context_example.py
  test/memories/context_creators/test_score_based.py
Labels: bug

#2024 fix:SubprocessInterpreter does not successfully provide code
  camel/interpreters/docker_interpreter.py
  camel/interpreters/e2b_interpreter.py
  camel/interpreters/subprocess_interpreter.py
Labels: bug

#1884 chore: update dependency for owl
  .github/ISSUE_TEMPLATE/bug_report.yml
  camel/__init__.py
  docs/conf.py
  docs/key_modules/loaders.md
  pyproject.toml
  uv.lock
Labels: enhancement

#1923 fix: O1 models not support system roles
  camel/models/openai_model.py
Labels: bug

#1961 feat: Support loading model configs from YAML and JSON files
  camel/models/model_factory.py
  examples/models/config_files/config.json
  examples/models/config_files/config.yaml
  examples/models/model_manger.py
  test/models/test_config_file/json_configs/claude2_config.json
  test/models/test_config_file/json_configs/claude2_openai_token_counter.json
  test/models/test_config_file/json_configs/gemini_1.5_flash_config.json
  test/models/test_config_file/json_configs/ollama_config.json
  test/models/test_config_file/json_configs/ollama_openai_token_counter.json
  test/models/test_config_file/json_configs/openai3.5_turbo_config.json
  test/models/test_config_file/json_configs/openai4o_config.json
  test/models/test_config_file/yaml_configs/claude2_config.yaml
  test/models/test_config_file/yaml_configs/claude2_openai_config.yaml
  test/models/test_config_file/yaml_configs/gemini_1.5_flash_config.yaml
  test/models/test_config_file/yaml_configs/ollama_config.yaml
  test/models/test_config_file/yaml_configs/ollama_openai_config.yaml
  test/models/test_config_file/yaml_configs/openai3.5_turbo_config.yaml
  test/models/test_config_file/yaml_configs/openai4o_config.yaml
  test/models/test_model_factory.py
Labels: New Feature

#2042 fix: python verifier does not handle string comparison properly
  camel/verifiers/python_verifier.py
Labels: bug

#1998 fix: pygithub issue
  camel/agents/repo_agent.py
  camel/toolkits/github_toolkit.py
  camel/verifiers/python_verifier.py
  test/toolkits/test_github_toolkit.py
  test/verifiers/test_python_verifier.py
Labels: bug

#2044 feat: add math verify as verifier
  camel/verifiers/__init__.py
  camel/verifiers/math_verifier.py
  examples/verifier/math_verifier_example.py
  pyproject.toml
  test/datasets/test_self_instruct_generator.py
  test/verifiers/test_math_verifier.py
  uv.lock
Labels: New Feature, Loong

#2009 refactor: unify the stdio&sse configuration of mcp server
  camel/toolkits/mcp_toolkit.py
  test/toolkits/test_mcp_toolkit.py
Labels: enhancement
